#+property: header-args:emacs-lisp :tangle init.el :comments org

* Abstract

Trying literate programming with my Emacs configuration. This is
inspired by http://alhassy.com/emacs.d/. Protesilaos
(https://protesilaos.com/) uses such a method as well. His
configuration (https://git.sr.ht/~protesilaos/dotfiles) is also a good
resource to learn about Emacs.

* Lexical Bindings

#+begin_src emacs-lisp :tangle "early-init.el" :comments no
  ;;; -*- lexical-binding: t -*-
#+end_src

#+begin_src emacs-lisp :comments no
  ;;; -*- lexical-binding: t -*-
#+end_src

* Custom File Location

It is good to place the custom file in =.emacs.d= directory. This way,
we have all the files related to Emacs in one single directory. Some
users do not like the idea of a custom file since Emacs' Custom writes
to it. However, I consider the custom file as a location that you can
add some machine-dependent settings. For example, you can specify the
location of a binary file. I find it helpful since I am using Emacs on
different computers and different OSes. Thus, keep a volatile and
local configuration file helps solve some specific issues.

#+begin_src emacs-lisp
  (setq custom-file (locate-user-emacs-file "custom.el"))
#+end_src

* Emacs Native Configurations

This part contains configurations about all Emacs native options and
built-in packages. This part does not depend on any third-party
packages.

** Android Environment Settings

#+begin_src emacs-lisp :tangle (if (eq system-type 'android) "early-init.el" "no")
  (setenv "PATH" (format "%s:%s" "/data/data/com.termux/files/usr/bin"
  		       (getenv "PATH")))
  (push "/data/data/com.termux/files/usr/bin" exec-path)
#+end_src

** COMMENT Set =find= on Windows :dependency:

# Since we use consult-everything and consult-fd on Windows, this is
# no longer necessary now.

Windows provides a find program which accepts different arguments than
the Linux one. Emacs works out-of-the-box with Linux find program, so
on Windows I have to tell Emacs where the find program is, one that
accepts Linux find program conventional arguments.

#+begin_src emacs-lisp
  (use-package grep
    :defer t
    :config
    (if (eq system-type 'windows-nt)
        (setq find-program "C:/msys64/usr/bin/find.exe")))
#+end_src

** COMMENT Package

I use =package.el= to manage almost all the packages I use, except those
are only available on GitHub. =package.el= is flexible since it can
easily be configured to use a local repository or a mirror. This is
really helpful when your network environment is not good.

#+begin_src emacs-lisp
  (require 'package)
  (setq package-archives
        '(
          ("gnu" . "https://elpa.gnu.org/packages/")
          ("melpa" . "https://melpa.org/packages/")
          ("nongnu" . "https://elpa.nongnu.org/nongnu/")
          ;; ("melpa-stable" . "https://stable.melpa.org/packages/")

          ;; use local repository
          ;; ("local-melpa" . "~/elpa-mirror-master/melpa/")
          ;; ("local-gnu" . "~/elpa-mirror-master/gnu/")
          ;; ("local-nongnu" . "~/elpa-mirror-master/nongnu/")

          ;; Use either 163 or tsinghua mirror repository when official melpa
          ;; is slow or shutdown.

          ;; ;; {{ Option 1: 163 mirror repository:
          ;; ("gnu" . "https://mirrors.163.com/elpa/gnu/")
          ;; ("melpa" . "https://mirrors.163.com/elpa/melpa/")
          ;; ("melpa-stable" . "https://mirrors.163.com/elpa/stable-melpa/")
          ;; ("nongnu" . "https://mirrors.163.com/elpa/nongnu/")
          ;; ;; }}

          ;; ;; {{ Option 2: tsinghua mirror repository
          ;; ;; @see https://mirror.tuna.tsinghua.edu.cn/help/elpa/ on usage:
          ;; ;; ("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
          ;; ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
          ;; ("melpa-stable" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/stable-melpa/")
          ;; }}

          ;; gitlab mirror
          ;; ("melpa" . "https://gitlab.com/d12frosted/elpa-mirror/raw/master/melpa/")
          ;; ("org"   . "https://gitlab.com/d12frosted/elpa-mirror/raw/master/org/")
          ;; ("gnu"   . "https://gitlab.com/d12frosted/elpa-mirror/raw/master/gnu/")
          ))
  ;; (package-refresh-contents)
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

** Garbage Collection Settings

Adjust garbage collection thresholds during startup, and restore it
after startup. It is said that this reduces the boot time, but I have
not seen any observable change.

#+begin_src emacs-lisp :tangle "early-init.el"
  (setq gc-cons-threshold most-positive-fixnum
        gc-cons-percentage 0.5)

  (defvar my/file-name-handler-alist file-name-handler-alist)
  (defvar my/vc-handled-backends vc-handled-backends)

  (setq file-name-handler-alist nil
        vc-handled-backends nil)

  (add-hook 'emacs-startup-hook
            (lambda ()
              (setq gc-cons-threshold (* 1024 1024 128)
                    gc-cons-percentage 0.2
                    file-name-handler-alist my/file-name-handler-alist
                    vc-handled-backends my/vc-handled-backends)))
#+end_src

** Native Compilation

Native compilation tends to generate a lot of warnings, which
interrupts whatever work you are doing. Disabling them reduces
distraction.

#+begin_src emacs-lisp
  (when (native-comp-available-p)
    (setq native-comp-async-report-warnings-errors 'silent) ; Emacs 28 with native compilation
    (setq native-compile-prune-cache t)) ; Emacs 29
#+end_src

** Who am I?

#+begin_src emacs-lisp
  (setq user-full-name "Chang Xiaoduan"
        user-mail-address "drcxd@sina.com")
#+end_src

** Auto Backup

By default, Emacs will automatically generate a backup file every time
you edit an existing file. If your file name is =fname.txt=, then it
generates a backup file named =fname.txt=. This can quickly make the
directory messy, so I prefer disable this feature.

#+begin_src emacs-lisp
  (setq make-backup-files nil)
#+end_src

** Auto Save

Emacs can automatically save edited files after some certain idle
time. This feature is disabled by default. I would like to enable it
to prevent accidental loss of data. The idle time should not be too
short since this would incur frequently disk I/O.

#+begin_src emacs-lisp
  ;; auto-save-visited-interval must be set before
  ;; auto-save-visited-mode is enabled, otherwise, changing its value
  ;; does not take effect
  (setq auto-save-visited-interval 30)
  (auto-save-visited-mode 1)
#+end_src

** Auto Revert

I turn on auto-revert-mode because sometimes when a file is edited by
some external programs, edit it again and save it in Emacs will
conflict with the external changes. Enable auto-revert-mode eliminate
the chances of such problems.

#+begin_src emacs-lisp
  (use-package autorevert
    :init
    (setq auto-revert-verbose nil)
    :config
    (global-auto-revert-mode))
#+end_src

** System Time Locale

Use English for datetime string regardless of the operating system
language. Credit to this SO [[https://stackoverflow.com/questions/28913294/emacs-org-mode-language-of-time-stamps][post]].

#+begin_src emacs-lisp
  (setq system-time-locale "C")
#+end_src

** Completion

#+begin_src emacs-lisp
  (setq completion-ignore-case t)
#+end_src

** Emacs As Server

#+begin_src emacs-lisp
  (use-package server
    :init
    (setq server-client-instructions nil)
    :config
    (unless (server-running-p)
    (server-start)))
#+end_src

** Filling and Wrapping

#+begin_src emacs-lisp
  (setq-default truncate-lines t)
  ;; Enable wrapping after any Chinese characters
  ;; More information about this issue: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29364
  (setq word-wrap-by-category t)
  (use-package visual-wrap
    :defer t
    :config
    (global-visual-wrap-prefix-mode))
#+end_src

** Performance

Copied from [[https://emacsredux.com/blog/2026/04/07/stealing-from-the-best-emacs-configs/][Emacs Redux]].

#+begin_src emacs-lisp
  ;; Disable Bidirectional Text Scanning (Doom Emacs)
  (setq-default bidi-display-reordering 'left-to-right
                bidi-paragraph-direction 'left-to-right)
  (setq bidi-inhibit-bpa t)

  ;; Skip Fontification During Input (Doom Emacs)
  (setq redisplay-skip-fontification-on-input t)

  ;; Increase Process Output Buffer for LSP (Doom, Purcell, Centaur)
  (setq read-process-output-max (* 4 1024 1024)) ; 4MB

  ;; Don’t Render Cursors in Non-Focused Windows (Doom Emacs)
  (setq-default cursor-in-non-selected-windows nil)
  (setq highlight-nonselected-windows nil)
#+end_src

** simple

Tab could be translated to different length spaces by different
editors. To avoid such a difference, simply avoid using tab.

#+begin_src emacs-lisp
  (use-package simple
    :init
    (setq-default indent-tabs-mode nil)
    ;; The following code is copied from Emacs Redux
    ;; https://emacsredux.com/blog/2026/04/07/stealing-from-the-best-emacs-configs/
    (setq save-interprogram-paste-before-kill t ;; Save the Clipboard Before Killing (Purcell, Prot, Centaur)
          kill-do-not-save-duplicates t ;; No Duplicates in the Kill Ring (Doom, Prot)
          set-mark-command-repeat-pop t)
    :bind
    (("C-c O" . blink-matching-open)
     ("C-c S" . shell-command)))
#+end_src

** Documentation Style

Emacs 28 supports syntax highlighting for documentations in comments.

#+begin_src emacs-lisp
  (setq-default c-doc-comment-style
                '((java-mode . javadoc)
                  (pike-mode . autodoc)
                  (c-mode    . doxygen)
                  (c++-mode  . doxygen)))
#+end_src

** Menu, Tool, and Scroll Bar

#+begin_src emacs-lisp :tangle "early-init.el"
  (use-package menu-bar
    :config
    (menu-bar-mode -1))

  (use-package tool-bar
    :config
    (tool-bar-mode -1))

  (use-package scroll-bar
    :config
    (scroll-bar-mode -1))
#+end_src

** Mode Line

#+begin_src emacs-lisp
  (setq display-time-24hr-format t)
  (display-time)
  (column-number-mode)
  ;; put mode lines at the top of buffers
  ;; (setq-default header-line-format mode-line-format)
  ;; (setq-default mode-line-format nil)

  ;; NOTE: I give up this configuration since the header line is also
  ;; used by some special buffer, for example, org-edit-special. In such
  ;; a buffer, I lose all the information provided by the mode
  ;; line. This is not acceptable so I switch back to the bottom mode
  ;; line setting.
#+end_src

** Splash Screen

By default, Emacs shows a welcome screen every time it is
launched. This might be useful to new Emacs users, but for experienced
users, displaying the =*scratch*= buffer by default may be more
productive. You could also execute the command =about-emacs= to display
the splash screen manually.

#+begin_src emacs-lisp
  (setq inhibit-splash-screen t)
#+end_src

** window

#+begin_src emacs-lisp
  (use-package window
    :init
    (setq switch-to-buffer-in-dedicated-window 'pop
          switch-to-buffer-obey-display-actions t)
          ;; window-sides-slots '(1 0 0 1))
    :bind
    ("C-c b" . switch-to-buffer)
    :config
    (setq display-buffer-alist
          '(((or "\\*\\(Backtrace\\|Warnings\\|Compile-Log\\|Messages\\|Bookmark List\\|Occur\\|eldoc\\)\\*"
                 (major-mode . bookmark-bmenu-mode))
             (display-buffer-in-side-window)
             (window-height . 0.25)
             (side . bottom)
             (slot . 0))
            ((or "\\*\\(grep\\|xref\\|find\\)\\*"
                 (major-mode . grep-mode))
             (display-buffer-in-side-window)
             (window-height . 0.25)
             (side . bottom)
             (slot . 0))
            ("\\*Async Shell Command\\*.*"
             (display-buffer-in-side-window)
             (window-height . 0.25)
             (side . bottom)
             (slot . 1))
            ("^\\*.*eshell\\*$"
             (display-buffer-in-side-window)
             (side . bottom)
             (window-height . 0.25)
             (slot . 1))
            ((or (major-mode . Info-mode)
                 (major-mode . help-mode))
             (display-buffer-in-side-window)
             (window-width . 80)
             (side . left)
             (slot . 0))
            ((or (major-mode . dired-mode)
                 (major-mode . process-menu-mode)
                 "*IBuffer*")
             (display-buffer-in-side-window)
             (window-width . 0.381)
             (side . left)
             (slot . 1)))))

  ;; Proportional Window Resizing (Purcell, Prot)
  (setq window-combination-resize t)

  (use-package winner
    :config
    (winner-mode +1))
#+end_src

** help

#+begin_src emacs-lisp
  ;; Auto-Select Help Windows (Prot)
  (use-package help
    :init
    (setq help-window-select t))
#+end_src

** text-mode

Enable proportional font and auto filling in text mode.

#+begin_src emacs-lisp
  (use-package text-mode
    :defer t
    :hook
    ((text-mode . variable-pitch-mode)
     (text-mode . auto-fill-mode)))
#+end_src

** HTML Rendering

Use the same width as ~fill-column~ for ~shr-width~.

#+begin_src emacs-lisp
  (use-package shr
    :defer t
    :init
    (setq shr-width fill-column))
#+end_src

** Blink Cursor Mode

I find the blinking cursor distracting and annoying. If I want to
figure out the location of the cursor, I can use =C-l=. Better, I can
use avy commands to move the cursor to where I want it to be. Why
should I care where the cursor is?

#+begin_src emacs-lisp
  (use-package frame
    :config
    (blink-cursor-mode -1))
#+end_src

** uniquify

When two buffers of the same name are opened, Emacs has to uniquify
them so you can distinguish between them.

#+begin_src emacs-lisp
  (use-package uniquify
    :defer t
    :init
    (setq uniquify-buffer-name-style 'forward
          uniquify-after-kill-buffer-p t
          uniquify-strip-common-suffix t
          uniquify-ignore-buffers-re "^\\*"))
#+end_src

** ibuffer

ibuffer is a buffer list all opened buffers in Emacs. You can use it
to manage these buffers just as you manage files in dired.

#+begin_src emacs-lisp
  (use-package ibuffer
    :defer t
    :init
    (setq ibuffer-default-shrink-to-minimum-size t)
    :bind
    ("C-x C-b" . ibuffer))
#+end_src

** Dired

dired is the facility Emacs uses to manage files. It's the file
explorer of Emacs. You can perform many file operations in dired.

#+begin_src emacs-lisp
  (use-package dired
    :init
    (setq dired-kill-when-opening-new-dired-buffer t
          dired-guess-shell-alist-user '(("\\.pdf\\'" "okular &")))
    (defun dired-mode-setup ()
      "Setup dired."
      ;; global-auto-revert-mode does not work for dired
      (auto-revert-mode)
      (dired-hide-details-mode))
    :hook
    (dired-mode . dired-mode-setup))

  (use-package dired-x
    :after dired)
#+end_src

** Repeat Mode

Activate repeat mode to move among windows and repeat =M-x= commands.

#+begin_src emacs-lisp
  (use-package repeat
    :config
    (repeat-mode))
#+end_src

** display-fill-column-indicator

#+begin_src emacs-lisp
  (use-package display-fill-column-indicator
    :defer t
    :hook
    (prog-mode . display-fill-column-indicator-mode))
#+end_src

** hideshow

#+begin_src emacs-lisp
  (use-package hideshow
    :defer t
    :diminish hs-minor-mode
    :hook
    (prog-mode . hs-minor-mode))
#+end_src

** hl-line

#+begin_src emacs-lisp
  (use-package hl-line
    :defer t
    :hook
    (prog-mode . hl-line-mode))
#+end_src

** prog-mode

#+begin_src emacs-lisp
  (use-package prog-mode
    :init
    (defun prog-mode-setup ()
      (setq show-trailing-whitespace t))
    :hook
    (prog-mode . prog-mode-setup))
#+end_src

** project

#+begin_src emacs-lisp
  (use-package project
    :defer t
    :init
    (setq project-vc-extra-root-markers '(".project")))
#+end_src

** vc-svn

#+begin_src emacs-lisp
  (use-package vc-svn
    :defer t
    :config
    (setq vc-svn-annotate-switches "-x --ignore-eol-style"))
#+end_src

** nXML Mode

By default, nXML mode does not support hide and show certain blocks
(sections/nodes), this piece of code add this feature using hs-minor
mode.

Credit: https://stackoverflow.com/questions/944614/emacs-does-hideshow-work-with-xml-mode-sgml-mode

#+begin_src emacs-lisp
  (use-package nxml-mode
    :defer t
    :config
    (add-to-list 'hs-special-modes-alist
                 (list 'nxml-mode
                       "<!--\\|<[^/>]*[^/]>"
                       "-->\\|</[^/>]*[^/]>"
                       "<!--"
                       'nxml-forward-element
                       nil))
    :hook
    (nxml-mode . hs-minor-mode))
#+end_src

** Gnus

Gnus is a complicated piece of software. It can be used to read email
and RSS feeds, for example.

It might be powerful, but it is difficult to set up correctly. For
email, it is complicated to set up with an email server which requires
two-step authentication. For RSS feeds, I have not figure out a way to
set up in a declarative way. That is, I can only set up RSS feeds with
an interactive process: by executing
~gnus-group-make-rss-group~. Maybe I can read its source code and see
which states it changes.

#+begin_src emacs-lisp
  (use-package gnus
    :defer t
    :bind
    (:map gnus-summary-mode-map
          ("v n" . gnus-summary-next-subject)
          ("v p" . gnus-summary-prev-subject)
          (:repeat-map gnus-summary-mode-repeat-map
                       ("n" . gnus-summary-next-subject)
                       ("p" . gnus-summary-prev-subject)))
    :config
    (setopt
     ;; mail-user-agent 'gnus-user-agent
     ;; read-mail-command #'gnus

     gnus-save-newsrc-file nil
     gnus-read-newsrc-file nil

     gnus-interactive-exit nil)

    (setq
     gnus-select-method '(nnnil "")

     ;; Receving mails
     gnus-secondary-select-methods
     '((nnimap
        "sina"
        (nnimap-stream tls)
        (nnimap-address "imap.sina.com")))

     ;; Send mails
     smtpmail-smtp-server "smtp.sina.com"
     smtpmail-stream-type 'starttls
     ;; Without this, sending fails for authorization reasons
     smtpmail-servers-requiring-authorization "sina"
     send-mail-function 'smtpmail-send-it))
#+end_src

** ediff

#+begin_src emacs-lisp
  (use-package ediff
    :defer t
    :init
    (setq ediff-keep-variants nil
          ediff-show-clashes-only t
          ediff-split-window-function 'split-window-horizontally))
#+end_src

** imenu

#+begin_src emacs-lisp
  (use-package imenu
    :defer t
    :init
    (setq imenu-max-item-length 'Unlimited))
#+end_src

** isearch

#+begin_src emacs-lisp
  (use-package isearch
    :defer t
    :init
    (setq isearch-lazy-count t))
#+end_src

** dictionary

#+begin_src emacs-lisp
  (use-package dictionary
    :defer t
    :init
    (setq dictionary-server "dict.org")
    :bind
    ("C-c d" . dictionary-lookup-definition))
#+end_src

** hi-lock

I am trying to use hi-lock to replace symbol highlighting. To
highlight a symbol, either use ~hi-lock-face-symbol-at-point~ or
~hi-lock-face-buffer~ with a regular expression. To remove highlighting
of a symbol, use ~hi-lock-unface-buffer~. To remove all the symbol
highlighting in the buffer, turn off ~hi-lock-mode~.

The idea of using this package for symbol highlighting and the
function ~toggle-hi-lock-symbol-at-point~ comes from [[https://www.jamescherti.com/emacs-symbol-highlighting-built-in-functions/][James Cherti]].

#+begin_src emacs-lisp
  (use-package hi-lock
    :defer t
    :diminish hi-lock-mode
    ;; :init
    ;; (defun toggle-hi-lock-symbol-at-point ()
    ;;   "Toggle highlighting for the symbol at point."
    ;;   (interactive)
    ;;   (when-let* ((regexp (find-tag-default-as-symbol-regexp)))
    ;;     (if (member regexp (hi-lock--regexps-at-point))
    ;;         ;; Unhighlight symbol at point
    ;;         (hi-lock-unface-buffer regexp)
    ;;       ;; Highlight symbol at point
    ;;       (hi-lock-face-symbol-at-point))))
    :bind
    (("C-c s p" . hi-lock-face-symbol-at-point)
     ("C-c s r" . hi-lock-unface-buffer)))
#+end_src

** minibuffer

#+begin_src emacs-lisp
  (use-package minibuffer
    :bind
    ("C-<tab>" . completion-at-point))
#+end_src

** windmove

Learned about this feature from this post, it feels quite good.

#+begin_src emacs-lisp
  (use-package windmove
    :config
    (windmove-default-keybindings))
#+end_src

** Personal Code

The code I write but not enough for a package.

#+begin_src emacs-lisp
  (defun my/config ()
    "Open init.org."
    (interactive)
    (find-file (locate-user-emacs-file "init.org")))

  (defun my/find-line-matching (file regex)
    "Return the first line in FILE whose text matches REGEX, or nil."
    (with-temp-buffer
      (insert-file-contents file)
      (goto-char (point-min))
      (when (re-search-forward regex nil t)
        (buffer-substring-no-properties (line-beginning-position)
                                        (line-end-position)))))
#+end_src

When working on Windows, sometimes I encounter files containing mixed
EOL characters. This would make some lines ended with additional
=^M=. To hide these annoying characters, I use the following function.

#+begin_src emacs-lisp
  (defun remove-dos-eol ()
    "Do not show ^M in files containing mixed UNIX and DOS line endings."
    (interactive)
    (setq buffer-display-table (make-display-table))
    (aset buffer-display-table ?\^M []))
#+end_src

*** Mottoes

# TODO: Make this a package

I would like the welcome message displayed in the scratch buffer be
some mottoes selected randomly from a pre-defined list.

#+begin_src emacs-lisp
  (defun my/process-raw-mottoes (lines &optional not-comment)
    "Process motto strings so that they could be displayed in the
    scratch buffer."
    (let ((ret ""))
      (dolist (line lines ret)
        (setq ret (format "%s%s%s\n"
                          ret
                          (if not-comment "" ";; ")
                          line)))))

  (defvar my/raw-mottoes
    '(("困于心衡于虑而后作" "征于色发于声而后喻")
      ("学而不思则罔" "思而不学则殆")
      ("生于忧患" "死于安乐")
      ("与其感慨路难行" "不如马上出发")
      ("不以物喜 不以己悲" "先天下之忧而忧" "后天下之乐而乐")
      ("悟已往之不谏" "知来者之可追")
      ("抽象")
      ("未来从今天开始")
      ("革命的道路" "同世界上一切事物活动的道路一样" "总是曲折 不是笔直的")
      ("老骥伏枥 志在千里" "烈士暮年 壮心不已")
      ("存地失人 人地皆失" "存人失地 人地皆存")
      ("胜兵先胜而后求战" "败兵先战而后求胜")
      ("胜可知而不可为")
      ("等死 死国可乎")
      ("冰冻三尺 非一日之寒")
      ("但行好事" "莫问前程")
      ("今我何功德" "曾不事农桑")
      ("All problems in computer science can be solved by another level of indirection,"
       "except for the problem of too many layers of indirection.") ;; David Wheeler
      ("希望越大 失望越大" "能力越小 责任越小")
      ("人固有一死" "或重于泰山 或轻于鸿毛" "用之所趋异也")
      ("水至清则无鱼" "人至察则无徒")
      ("是我们改变了世界" "还是世界改变了我和你")
      ("君子求诸己" "小人求诸人")
      ("君子和而不同" "小人同而不和")
      ("让子弹飞一会儿")
      ("鞠躬尽瘁" "死而后已")
      ("塞翁失马" "焉知非福")
      ("福兮祸之所倚" "祸兮福之所伏")
      ("人生代代无穷已" "江月年年望相似")
      ("担当生前事" "何计身后评")
      ("The spirit is willing" "but the flesh is weak")
      ("Res severa verum gaudium")
      ("天行健 君子以自强不息" "地势坤 君子以厚德载物")))

  (setq initial-scratch-message
        (concat ";; Hello, " user-full-name "\n\n"
                (my/process-raw-mottoes (seq-random-elt my/raw-mottoes))
                "\n"))

  (defun my/show-motto ()
    (interactive)
    (message (my/process-raw-mottoes
              (seq-random-elt my/raw-mottoes)
              t)))
#+end_src

*** Unreal :dependency:

# TODO: make this a package

I am working with Unreal Engine, using Emacs + clangd + lsp-mode as my
development environment. I find that I frequently execute some
operations on my Unreal project, such as generate compilation
database, generate header files, build the project and debug the
project. To accelerate these processes, I developed the following
routines.

Most of the operations use the Unreal Build Tool (UBT). All operations
must specify a target and a platform. These variables are defined for
convenience.

Unreal Header Tool (UHT) is a program which scans user code and
generate code to implement the reflection code. The source code is
marked with some macros which expands to file name and line
number. UHT generates code which substitutes those macros. As a
result, once the macro's location has changed, the file will fail the
compilation. However, changing of line number is frequent. This makes
clangd fail to compile the code, thus providing less useful
information when editing. The solution is to generate header every time
some macro's line number has changed.

#+begin_src emacs-lisp
  (defvar my/ubt-location nil "Unreal Build Tool executable location.")

  (defvar my/ue-profiles
    '("Debug" "DebugGame" "Development" "Test" "Shipping")
    "A list of frequently used optimization levels for Unreal projects.")

  (defvar my/ue-platforms '("Win64")
    "A list of frequently used platforms for Unreal projects.")

  (defun my/build-ubt-op-string (project target profile platform &optional operation)
    "Return a string that is ready to execute in the shell. If `operation' is
  `nil', then UBT will execute the default operation: build."
    (format-message "%s %s %s %s %s %s"
                    my/ubt-location
                    project
                    target
                    profile
                    platform
                    (or operation "")))

  (defun my/unreal-read-input ()
    "Read input that is frequently used in UBT operations."
    (let ((completion-ignore-case t))
      (list (read-file-name "Project file path: ")
             (read-string "Target: ")
             (completing-read "Profile: " my/ue-profiles nil nil)
             (completing-read "Platform: " my/ue-platforms nil nil))))

  (defun my/unreal-build-project (project target profile platform)
    "Build an Unreal project."
    (interactive (my/unreal-read-input))
    (async-shell-command (my/build-ubt-op-string project target profile platform)))

  ;; clangd + lsp-mode requires a compilation database to work. UBT
  ;; provides a mode which generates the compilation database.

  (defun my/unreal-generate-clang-database (project target profile platform)
    "Generate compilation database for an Unreal project."
    (interactive (my/unreal-read-input))
    (async-shell-command
     (my/build-ubt-op-string project target profile platform "-mode=GenerateClangDatabase")))

  (defun my/unreal-generate-header-file (project target profile platform)
    "Generate header files for specified Unreal project."
    (interactive (my/unreal-read-input))
    (async-shell-command
     (my/build-ubt-op-string project opt platform editor "-SkipBuild")))
#+end_src

*** COMMENT Build Ignore

# This code seems useless now

This piece of code provides the function ~my/build-ignore~ which
generates the =.ignore= file for git or fd using a description that
lists the files should not be ignored. The generated =.ignore= file
will ignore everything at the beginning. The given description is a
multiple-line string, where each line is a directory relative to the
=.ignore= file. Everything inside each given directory will not be
ignored. The function returns a string that is the content of the
=.ignore= file.

I create this function since writing =.ignore= file by hand using such
exception rules is tedious and error prone.

#+begin_src emacs-lisp
  (defun my/build-ignore--new-node (name parent)
    "Create a new node that represents a direcotry. `NAME' is a string and
  `PARENT' is a node created by this function. For the root node, `PARENT'
  should be `nil'."
    `(:name ,name
            :children ,(make-hash-table :test 'equal)
            :parent ,parent))

  (defun my/build-ignore--build-dir-tree-iter (parent names)
    "Auxliary function that helps build a tree structure that represents the
  relationship between the directories mentioned by the
  description. `PARENT' is the parent node of the first directiory in
  `NAMES'. `NAMES' is a list of directory names where the each following
  element is the direct child directory of its prior element.."
    (when names
      (let* ((name (car names))
             (children (plist-get parent :children))
             (node (gethash name children)))
        (if node
            (my/build-ignore--build-dir-tree-iter node (cdr names))
          (let ((new-node (my/build-ignore--new-node name parent)))
            (puthash name new-node children)
            (my/build-ignore--build-dir-tree-iter new-node (cdr names)))))))

  (defun my/build-ignore--build-dir-tree (desc)
    "Build a tree structure represents the relationship of the directories
  described by `DESC'."
    (let ((lines (split-string desc "\n"))
          (root (my/build-ignore--new-node "" nil)))
      (dolist (line lines)
        (let ((dirs (split-string line "/")))
          (my/build-ignore--build-dir-tree-iter root dirs)))
      root))


  (defun my/build-ignore--traverse-tree (tree iter)
    "Helper function that calls `ITER' on each node of `TREE', including the
  root node."
    (funcall iter tree)
    (maphash (lambda (key value)
               (my/build-ignore--traverse-tree value iter))
             (plist-get tree :children)))

  (defun my/build-ignore--build-full-path (node path)
    "Helper function that returns the full path starting from the root to the
  current node. `NODE' is the node that holds the ending directory. `PATH'
  is an iterative argument, used to accumulate the in construction full
  path."
    (let ((parent (plist-get node :parent)))
      (if parent
          (my/build-ignore--build-full-path parent (format "%s/%s" (plist-get node :name) path))
        (format "!%s" path))))

  (defun my/build-ignore (desc)
    "Generate the content of an .ignore file. Every file is ignored at the
  very beginning. `DESC' is a string of multiple lines where each line is
  a directory relative to the .ignore file. All files under each directory
  mentioned will not be ignored. For example:

  src/
  config/
  data/scripts/

  Note that the ending slash is not necessary. Each line can also begins
  with a starting slash."
    (let ((ignore "*"))
      (my/build-ignore--traverse-tree
       (my/build-ignore--build-dir-tree desc)
       (lambda (node)
         ;; build node's full dir
         (unless (string= (plist-get node :name) "")
           (let* ((children (plist-get node :children))
                  (is-leaf (= (hash-table-count children) 0))
                  (full-path (my/build-ignore--build-full-path node "")))
             (setq ignore (format "%s\n%s" ignore full-path))
             (if is-leaf (setq ignore (format "%s\n%s**" ignore full-path)))))))
      ignore))
#+end_src

** Key Bindings

#+begin_src emacs-lisp
  (global-set-key (kbd "C-c e") 'eval-region)
  (global-set-key (kbd "C-c k") 'kill-buffer)
#+end_src

* Third-Party Packages

** elpaca

Using elpaca requires disabling the built-in package manager.

#+begin_src emacs-lisp :tangle "early-init.el"
  (setq package-enable-at-startup nil)
#+end_src


#+begin_src emacs-lisp
  (defvar elpaca-installer-version 0.12)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-sources-directory (expand-file-name "sources/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                                :ref nil :depth 1 :inherit ignore
                                :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                                :build (:not elpaca-activate)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-sources-directory))
         (build (expand-file-name "elpaca/" elpaca-builds-directory))
         (order (cdr elpaca-order))
         (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (<= emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
          (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                    ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                    ,@(when-let* ((depth (plist-get order :depth)))
                                                        (list (format "--depth=%d" depth) "--no-single-branch"))
                                                    ,(plist-get order :repo) ,repo))))
                    ((zerop (call-process "git" nil buffer t "checkout"
                                          (or (plist-get order :ref) "--"))))
                    (emacs (concat invocation-directory invocation-name))
                    ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                          "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                    ((require 'elpaca))
                    ((elpaca-generate-autoloads "elpaca" repo)))
              (progn (message "%s" (buffer-string)) (kill-buffer buffer))
            (error "%s" (with-current-buffer buffer (buffer-string))))
        ((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))

  ;; Uncomment for systems which cannot create symlinks:
  (if (eq system-type 'windows-nt)
      (elpaca-no-symlink-mode))

  (elpaca elpaca-use-package
    ;; Enable Elpaca's use-package support
    (elpaca-use-package-mode))
  ;; Block until package is installed/activated so we can use it at the top-level below.
  (elpaca-wait)
#+end_src

** Other Packages

*** compat

#+begin_src emacs-lisp
  (use-package compat
    :ensure (:repo "https://github.com/emacs-compat/compat"))
  (elpaca-wait)
#+end_src

*** Appearance

**** Diminish

I am using the built-in mode line, and it displays a symbol for all
the activated minor modes. This could makes the mode line messy,
because usually we have lots of minor modes turned on but we do not
need the visual cue on the mode line to tell us they are
enabled. Diminish is a good package to solve this problem.

#+begin_src emacs-lisp
  (use-package diminish
    :demand t
    :ensure (:wait t))

  (use-package face-remap
    :defer t
    :ensure nil
    :diminish buffer-face-mode)

  (use-package eldoc
    :defer t
    :ensure nil
    :diminish eldoc-mode)

  (use-package abbrev
    :defer t
    :ensure nil
    :diminish abbrev-mode)
#+end_src

**** Unicode Support :dependency:

#+begin_src emacs-lisp :noweb yes
  (use-package unicode-fonts
    :ensure t
    :config
    (unicode-fonts-setup))
#+end_src

**** Themes

***** Modus Themes

#+begin_src emacs-lisp
  ;; (use-package standard-themes :ensure t)
  ;; (use-package ef-themes :ensure t)
  (use-package modus-themes
    :ensure t
    :defer t
    :preface
    (when (featurep 'modus-themes)
      (unload-feature 'modus-themes))
    :init
    (setq modus-themes-italic-constructs t
          modus-themes-bold-constructs nil
          modus-themes-mixed-fonts t
          modus-themes-variable-pitch-ui t
          modus-themes-headings '((0 . (variable-pitch 1.61803))
                                  (1 . (variable-pitch 1.38196))
                                  (2 . (variable-pitch 1.23607))
                                  (3 . (variable-pitch 1.1459))
                                  (4 . (variable-pitch 1.09017))
                                  (5 . (variable-pitch 1.05573))
                                  (6 . (variable-pitch 1.03444))
                                  (7 . (variable-pitch 1.02129))
                                  (t . (variable-pitch 1.0)))
          modus-themes-disable-other-themes t)
    :config
    (add-hook 'modus-themes-post-load-hook
              (lambda ()
                (if (eq system-type 'windows-nt)
                    (modus-themes-with-colors
                      (custom-set-faces
                       `(fill-column-indicator ((,c :height 1.0
                                                    :foreground ,border
                                                    :background ,bg-main))))))))
    (modus-themes-include-derivatives-mode))

  (defun my/select-modus-theme-using-os-theme ()
    "Select a proper modus theme depends on the os theme."
    (interactive)
    (let ((os-theme (my/find-line-matching "~/.config/kdeglobals" "LookAndFeelPackage")))
      (if (and os-theme
               (string-match "dark" os-theme))
          (modus-themes-select 'modus-vivendi)
        (modus-themes-select 'modus-operandi))))
#+end_src

**** Ligature

#+begin_src emacs-lisp
  (dolist (char/ligature-re
           `((?-  . ,(rx (or (or "-->" "-<<" "->>" "-|" "-~" "-<" "->")
                             (+ "-"))))
             (?/  . ,(rx (or (or "/==" "/=" "/>" "/**" "/*") (+ "/"))))
             (?*  . ,(rx (or (or "*>" "*/") (+ "*"))))
             (?<  . ,(rx (or (or "<<=" "<<-" "<|||" "<==>" "<!--" "<=>" "<||" "<|>" "<-<"
                                 "<==" "<=<" "<-|" "<~>" "<=|" "<~~" "<$>" "<+>" "</>"
                                 "<*>" "<->" "<=" "<|" "<:" "<>"  "<$" "<-" "<~" "<+"
                                 "</" "<*")
                             (+ "<")
                             (+ "-"))))
             (?:  . ,(rx (or (or ":?>" "::=" ":>" ":<" ":?" ":=") (+ ":"))))
             (?=  . ,(rx (or (or "=>>" "==>" "=/=" "=!=" "=>" "=:=") (+ "="))))
             (?!  . ,(rx (or (or "!==" "!=") (+ "!"))))
             (?>  . ,(rx (or (or ">>-" ">>=" ">=>" ">]" ">:" ">-" ">=") (+ ">"))))
             (?&  . ,(rx (+ "&")))
             (?|  . ,(rx (or (or "|->" "|||>" "||>" "|=>" "||-" "||=" "|-" "|>"
                                 "|]" "|}" "|=")
                             (+ "|"))))
             (?.  . ,(rx (or (or ".?" ".=" ".-" "..<") (+ "."))))
             (?+  . ,(rx (or "+>" (+ "+"))))
             (?\[ . ,(rx (or "[<" "[|")))
             (?\{ . ,(rx "{|"))
             (?\? . ,(rx (or (or "?." "?=" "?:") (+ "?"))))
             (?#  . ,(rx (or (or "#_(" "#[" "#{" "#=" "#!" "#:" "#_" "#?" "#(")
                             (+ "#"))))
             (?\; . ,(rx (+ ";")))
             (?_  . ,(rx (or "_|_" "__")))
             (?~  . ,(rx (or "~~>" "~~" "~>" "~-" "~@")))
             (?$  . ,(rx "$>"))
             (?^  . ,(rx "^="))
             (?\] . ,(rx "]#"))))
    (let ((char (car char/ligature-re))
          (ligature-re (cdr char/ligature-re)))
      (set-char-table-range composition-function-table char
                            `([,ligature-re 0 font-shape-gstring]))))
#+end_src

**** nerd-icons :dependency:

Add some fancy icons. Require nerd fonts:

https://www.nerdfonts.com/#home

#+begin_src emacs-lisp
  (use-package nerd-icons :ensure t :demand t
    :config
    (set-fontset-font t '(#xE000 . #xF8FF) nerd-icons-font-family))

  (use-package nerd-icons-completion
    :ensure t
    :after marginalia
    :config
    (nerd-icons-completion-mode)
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))

  (use-package nerd-icons-dired
    :ensure t
    :defer t
    :diminish nerd-icons-dired-mode
    :hook
    (dired-mode . nerd-icons-dired-mode))

  (use-package nerd-icons-corfu
    :ensure t
    :demand t
    :defer t
    :after corfu
    :init
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

  (use-package nerd-icons-ibuffer
    :ensure t
    :defer t
    :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src

**** spacious-padding

#+begin_src emacs-lisp
  ;;; This sample configuration comes from the package's manual

  (use-package spacious-padding
    :ensure t
    :init
    (spacious-padding-mode)
    :config
    (setq spacious-padding-widths
          '( :internal-border-width 16
             :right-divider-width 4
             :mode-line-width 4
             :fringe-width 8)
          spacious-padding-subtle-mode-line
          '( :mode-line-active error
             :mode-line-inactive shadow)))
#+end_src

**** lin

#+begin_src emacs-lisp
  (use-package lin
    :ensure t
    :init
    (setq lin-face 'lin-green
          lin-mode-hooks '(dired-mode-hook
                           grep-mode-hook
                           ibuffer-mode-hook
                           log-view-mode-hook
                           magit-log-mode-hook
                           occur-mode-hook
                           tabulated-list-mode-hook))
    (lin-global-mode 1))
#+end_src

**** foma

#+begin_src emacs-lisp
  (use-package foma
    :ensure (foma :type git :host github :repo "drcxd/foma" :files ("*.el"))
    :defer t
    :init
    (setq foma-default-height 140
          foma-default-weight 'regular
          foma-default-mono "IBM Plex"
          foma-default-variable 'by-date
          foma-default-chinese "LXGW WenKai"
          foma-fonts '(("Cascadia Code" zip "https://github.com/microsoft/cascadia-code/releases/download/v2407.24/CascadiaCode-2407.24.zip")
                       ("Victor Mono" zip "https://rubjo.github.io/victor-mono/VictorMonoAll.zip")
                       ("Aporetic" zip "https://github.com/protesilaos/aporetic/archive/refs/heads/main.zip")
                       ("IBM Plex Sans" zip "https://github.com/IBM/plex/releases/download/%40ibm%2Fplex-sans%401.1.0/ibm-plex-sans.zip")
                       ("IBM Plex Mono" zip "https://github.com/IBM/plex/releases/download/%40ibm%2Fplex-mono%401.1.0/ibm-plex-mono.zip")
                       ("IBM Plex Serif" zip "https://github.com/IBM/plex/releases/download/%40ibm%2Fplex-serif%401.1.0/ibm-plex-serif.zip")
                       ("JetBrains Mono" zip "https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip")
                       ("Red Hat" zip "https://github.com/RedHatOfficial/RedHatFont/archive/refs/heads/master.zip")
                       ("Source Code Pro" zip "https://github.com/adobe-fonts/source-code-pro/releases/download/2.042R-u%2F1.062R-i%2F1.026R-vf/TTF-source-code-pro-2.042R-u_1.062R-i.zip")
                       ("Source Sans" zip "https://github.com/adobe-fonts/source-sans/releases/download/3.052R/TTF-source-sans-3.052R.zip")
                       ("Intel One Mono" zip "https://github.com/intel/intel-one-mono/releases/download/V1.4.0/ttf.zip")
                       ("Clear Sans" zip "https://github.com/intel/clear-sans/archive/refs/heads/main.zip")
                       ("DejaVu" zip "https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip")
                       ("JuliaMono" zip "https://github.com/cormullion/juliamono/releases/download/v0.059/JuliaMono-ttf.zip")
                       ("Nerd Icons" zip "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/NerdFontsSymbolsOnly.zip")
                       ("LXGW WenKai" zip "https://github.com/lxgw/LxgwWenKai/releases/download/v1.510/lxgw-wenkai-v1.510.zip")
                       ("Noto Sans" google)
                       ("Noto Sans Mono" google)
                       ("Noto Serif" google)
                       ("Myna" zip "https://github.com/sayyadirfanali/Myna/archive/refs/heads/main.zip")
                       ("Maple Mono" zip "https://github.com/subframe7536/maple-font/releases/download/v7.9/MapleMono-CN-unhinted.zip")
                       ("Monaspace" zip "https://github.com/githubnext/monaspace/releases/download/v1.400/monaspace-frozen-v1.400.zip"))
          foma-profiles `((:name "Aporetic"
                                 :mono "Aporetic Sans Mono"
                                 :variable"Aporetic Serif")
                          (:name "Cascadia" :mono "Cascadia Code")
                          (:name "DejaVu"
                                 :mono "DejaVu Sans Mono" :variable "DejaVu Serif")
                          (:name "IBM" :mono "IBM Plex Mono" :variable "IBM Plex Serif")
                          (:name "Intel" :mono "Intel One Mono" :variable "Clear Sans")
                          (:name "JetBrains" :mono "JetBrains Mono")
                          (:name "Julia" :mono "JuliaMono")
                          (:name "Noto"
                                 :mono "Noto Sans Mono"
                                 :variable "Noto Serif")
                          (:name "Red Hat"
                                 :mono "Red Hat Mono"
                                 :variable "Red Hat Text")
                          (:name "Source"
                                 :mono "Source Code Pro"
                                 :variable "Source Sans 3")
                          (:name "Victor" :mono "Victor Mono")
                          (:name "Myna" :mono "Myna")
                          (:name "Monaspace"
                                 :mono "Monaspace Neon Frozen"
                                 :face-specs
                                 (((:family "Monaspace Neon Frozen")
                                   default
                                   fixed-pitch)
                                  ((:family "Monaspace Radon Frozen")
                                   font-lock-doc-face
                                   font-lock-comment-face
                                   font-lock-string-face)
                                  ((:family "Monaspace Argon Frozen")
                                   font-lock-function-name-face)
                                  ((:family "Monaspace Krypton Frozen")
                                   font-lock-type-face
                                   font-lock-constant-face
                                   font-lock-preprocessor-face)
                                  ((:family "Monaspace Xenon Frozen")
                                   font-lock-keyword-face)))
                          ,(if (eq system-type 'windows-nt)
                               '(:name "Input"
                                       :mono "InputMono"
                                       :variable "InputSerif")
                             '(:name "Input"
                                     :mono "Input Mono"
                                     :variable "Input Serif"))
                          (:name "Commit"
                                 :mono "CommitMono")
                          (:name "Maple Mono" :mono "Maple Mono CN" :chinese "Maple Mono CN"))))
#+end_src

**** COMMENT sleek-modeline

#+begin_src emacs-lisp
  (use-package sleek-modeline
    :ensure t
    :init
    (setq sleek-modeline-show-modal-state t)
    (defun my-clock-segment ()
      "Return the current time, or nil to display nothing."
      (format-time-string "%H:%M"))
    (defun my-pos-segment ()
      "Return the current cursor position."
      (format "[%d:%d]" (line-number-at-pos) (current-column)))
    (defun my-coding-system-segment ()
      "Return the current buffer file coding system."
      (format "%s" buffer-file-coding-system))
    :config
    (sleek-modeline-register-segment 'clock
                                     :fn 'my-clock-segment
                                     :side 'right
                                     :priority 5
                                     :separator t)
    (sleek-modeline-register-segment 'coding-system
                                     :fn 'my-coding-system-segment
                                     :side 'right
                                     :priority 4
                                     :separator t)
    (sleek-modeline-register-segment 'position
                                     :fn 'my-pos-segment
                                     :side 'right
                                     :priority 3
                                     :separator t)
    (sleek-modeline-mode 1))
#+end_src

*** Completion

**** vertico

Emacs has a tons of variables, commands and documents. When you
exploring them, vertico provides a much more informative interface for
you to browse those information.

#+begin_src emacs-lisp
  (use-package vertico
    :ensure t
    :demand t
    :init
    (vertico-mode)
    :config
    (setq read-extended-command-predicate #'command-completion-default-include-p
          enable-recursive-minibuffers t))
#+end_src

**** orderless

orderless allows the completion systems using a different completion
strategy. The default completion systems completes based on prefix
matching. orderless enable it to use a fuzzy matching strategy. This
is quite useful because you do not always remember exactly what you
want to search. Sometimes, you do not even know if the things in your
head exist or not, but you want to use the completions system as a
tool to verify your assumption. Orderless completion is really helpful
in these situations.

#+begin_src emacs-lisp
  (use-package orderless
    :ensure t
    :demand t
    :config
    (setq completion-styles '(orderless partial-completion basic)
          completion-category-defaults nil
          completion-category-overrides '((file (styles partial-completion)))))
#+end_src

**** marginalia

marginalia works together with vertico, it provides more information
of a variable or function in the completion interface. This may help
you locate your target more quickly.

#+begin_src emacs-lisp
  (use-package marginalia :ensure t
    :config
    (marginalia-mode))
#+end_src

**** consult

consult works together with vertico. It helps you complete among lots
of things, such as buffers, file contents, grep results, find results,
etc..

#+begin_src emacs-lisp
  (use-package consult
    :demand t
    :ensure t
    :init
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)
    (defun consult-ripgrep-with-prefix ()
      (interactive)
      (let ((current-prefix-arg '(4)))
        (call-interactively 'consult-ripgrep)))
    :config
    (setq consult-fontify-max-size 262144) ;; 262144 = 2 ^ 18
    (setq consult-preview-excluded-files '(".*epub"))

    ;; this handles problems when consult results contains
    ;; Chinese characters
    (if (eq system-type 'windows-nt)
        (progn
          ;; https://github.com/minad/consult/issues/572
          (add-to-list 'process-coding-system-alist
                       '("[rR][gG]" . (utf-8 . gbk-dos)))
          ;; https://github.com/minad/consult/issues/601
          (setq consult-find-args (concat find-program " . "))))
    (with-eval-after-load 'project
      (add-to-list 'project-switch-commands
                   '(consult-project-buffer "Consult buffer" "b"))
      (add-to-list 'project-switch-commands
                   '(consult-fd "Consult fd" "F")))
    :bind
    (([remap switch-to-buffer] . consult-buffer)
     ("C-c i" . consult-line)
     ("C-c r" . consult-ripgrep-with-prefix)
     ("C-c R" . consult-ripgrep)
     ("C-c I" . consult-imenu)
     ("C-c f" . consult-fd)
     ("C-c H" . consult-org-heading)
     ("C-c p" . consult-project-buffer)))

  (if (eq system-type 'windows-nt)
      (use-package consult-everything
        :ensure (:repo "https://github.com/jthaman/consult-everything")
        :after consult
        :bind
        ("C-c F" . consult-everything)))
#+end_src

**** embark

embark allows users perform certain tasks in the completion
interface. This reduces the number of operations users have to
perform. For example, when you are trying to delete a certain file,
you have to =find-file= to open the directory the file is located. Then
mark the file to be deleted in dired and finally execute the delete
operation. With embark, you can simply browse to the file in
completion system and then execute =embark-act= then use its delete file
function to delete the current completion candidate. Much more
convenient.

#+begin_src emacs-lisp
  (use-package embark
    :ensure t
    :defer t
    :bind ("<f6>" . embark-act)
    :config
    (add-to-list 'display-buffer-alist
                 '((major-mode . embark-collect-mode)
                   (display-buffer-in-side-window)
                   (window-height . 0.25)
                   (side . bottom)
                   (slot . 0))))
  (use-package embark-consult :defer t :ensure t)
#+end_src

**** corfu

corfu is a completion front end package. That is, it is responsible to
display the completion candidates on the screen.

#+begin_src emacs-lisp
  (use-package corfu
    :ensure t
    :init
    (setq corfu-auto nil
          corfu-cycle t
          corfu-quit-at-boundary nil
          corfu-quit-no-match nil
          corfu-preview-current nil
          corfu-excluded-modes '(gud-mode))
    ;; disalbe corfu in gud-mode, see
    ;; https://github.com/minad/corfu/issues/157 for more detail
    (defun corfu-enable-in-minibuffer ()
      "Enable Corfu in the minibuffer if `completion-at-point' is bound."
      (when (where-is-internal #'completion-at-point (list (current-local-map)))
        (corfu-mode 1)))
    (global-corfu-mode)
    (corfu-popupinfo-mode)
    :hook
    (minibuffer-setup . corfu-enable-in-minibuffer)
    :bind
    (:map corfu-map
          ("C-n" . corfu-next)
          ("C-p" . corfu-previous)
          ("<tab>" . corfu-next)
          ("S-<tab>" . corfu-previous)
          ("<backtab>" . corfu-previous)
          ("C-g" . corfu-quit)
          ("<escape>" . corfu-quit)
          ("SPC" . corfu-insert-separator)))

  (unless (display-graphic-p)
    (use-package corfu-terminal
        :ensure (:type git :host codeberg :repo "akib/emacs-corfu-terminal")
        :init
        (corfu-terminal-mode +1)))
#+end_src

**** cape

cape provides a set of completion backends. A completion back ends
decides what are the completion candidates.

#+begin_src emacs-lisp
  ;; (use-package company :defer t :ensure t)
  (use-package cape
    :ensure t
    :demand t
    :config
    (add-to-list 'completion-at-point-functions #'cape-abbrev)
    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-file)
    ;; (add-to-list 'completion-at-point-functions #'cape-elisp-block)
    ;; (add-to-list 'completion-at-point-functions #'cape-elisp-symbol)
    ;; (add-to-list 'completion-at-point-functions #'cape-history)
    ;; (add-to-list 'completion-at-point-functions #'cape-keyword)
    ;; (add-to-list 'completion-at-point-functions (cape-company-to-capf #'company-clang))
    )
#+end_src

**** Templates & Snippets

When programming, we have to write some boilerplate code: the
structure of the piece of code is conventional, we only need to
replace some key text in it, for example, the name of the variable.

There is a well-known package for this task: yasnippet. However, this
package is not maintained actively for more than two years (today is
2022-12-10, and its last commit time is 2020-06-04). Thus, I switch to
another package, tempel. Though it is a new package, it has its own
advantages. First, it relies on Emacs built-in Tempo library. Second,
its simple enough to learn and work with. Third, it is maintained
actively. However, since yasnippet is well-known, some other packages,
such as lsp-mode, depends on it somehow, so I still install it.

#+begin_src emacs-lisp
  (use-package tempel :defer t
    :ensure t
    :init
    ;; Setup completion at point
    (defun tempel-setup-capf ()
      ;; Add the Tempel Capf to `completion-at-point-functions'.
      ;; `tempel-expand' only triggers on exact matches. Alternatively use
      ;; `tempel-complete' if you want to see all matches, but then you
      ;; should also configure `tempel-trigger-prefix', such that Tempel
      ;; does not trigger too often when you don't expect it. NOTE: We add
      ;; `tempel-expand' *before* the main programming mode Capf, such
      ;; that it will be tried first.
      (setq-local completion-at-point-functions
                  (cons #'tempel-expand
                        completion-at-point-functions)))
    :bind
    (("<f7>" . tempel-insert)
     ("<f8>" . tempel-complete))
    :hook
    ((prog-mode . tempel-setup-capf)
     (text-mode . tempel-setup-capf)))

  ;; (use-package yasnippet
  ;;   :ensure t
  ;;   :diminish yas-minor-mode
  ;;   :defer t
  ;;   :hook
  ;;   (prog-mode . yas-minor-mode)
  ;;   :bind
  ;;   ("C-c Y" . yas-reload-all))
#+end_src

*** org-mode

#+begin_src emacs-lisp
  (use-package org :defer t
    :ensure '(org :type git
                  :repo "https://code.tecosaur.net/tec/org-mode.git/"
                  :branch "dev")
    :init
    (defvar my/org-babel-languages (list '(C . t)
                                         '(racket . t)
                                         '(emacs-lisp . t)
                                         '(dot . t)))
    :hook
    ((emacs-startup . (lambda ()
                        (org-babel-do-load-languages 'org-babel-load-languages my/org-babel-languages)))
     (org-mode . org-latex-preview-mode))
    :config
    (setq org-ellipsis "…"
          org-auto-align-tags nil
          org-tags-column 0
          org-catch-invisible-edits 'show-and-error
          org-special-ctrl-a/e t
          org-hide-emphasis-markers nil
          org-pretty-entities nil
          org-babel-C-compiler "clang"
          org-babel-C++-compiler "clang++"
          ;; org-edit-special will replace the current window with the
          ;; special window
          org-src-window-setup 'current-window)
    (add-to-list 'org-modules 'org-habit t)
    ;; The following code makes org emphasis markup covers more lines
    ;; (setcar (nthcdr 4 org-emphasis-regexp-components) 5)
    ;; (org-set-emph-re 'org-emphasis-regexp-components org-emphasis-regexp-components)
    ;; latex preview use dvilualatex and dvisvgm
    ;; (push '(luasvgm
    ;;         :programs ("dvilualatex" "dvisvgm")
    ;;         :descrition "dvi > svg"
    ;;         :message "you need to install the programs: divlualatex dvisvgm"
    ;;         :image-input-type "dvi"
    ;;         :image-output-type "svg"
    ;;         :image-size-adjust (1.7 . 1.5)
    ;;         :latex-compiler
    ;;         ("dvilualatex -shell-escape -interaction nonstopmode -output-directory %o %f")
    ;;         :image-converter
    ;;         ("dvisvgm %f --no-fonts --exact-bbox --scale=%S --output=%O"))
    ;;       org-preview-latex-process-alist)
    ;; (setq org-preview-latex-default-process 'luasvgm)
    ;; latex export use lualatex
    ;; (setq org-latex-pdf-process '("lualatex -shell-escape -interaction=nonstopmode -output-directory=%o %f"))
    ;; org latex preview settings
    (setq
     org-latex-preview-mode-display-live t
     org-latex-preview-mode-update-delay 0.25))
#+end_src

**** Exporting Chinese Paragraph to HTML

Due to the difference between English and Chinese, there are some
extra spaces in exported Chinese paragraph when exporting to
HTML. These spaces are necessary since English uses spaces to separate
words, but Chinese don't. We have to override this behavior.

#+begin_src emacs-lisp
  (defadvice org-html-paragraph (before org-html-paragraph-advice
                                        (paragraph contents info) activate)
    "Join consecutive Chinese lines into a single long line without
     unwanted space when exporting org-mode to html."
    (let* ((origin-contents (ad-get-arg 1))
           (fix-regexp "[[:multibyte:]]")
           (fixed-contents
            (replace-regexp-in-string
             (concat
              "\\(" fix-regexp "\\) *\n *\\(" fix-regexp "\\)") "\\1\\2" origin-contents)))
      (ad-set-arg 1 fixed-contents)))
#+end_src

**** Delete Link

This is inspired by this [[https://emacs.stackexchange.com/a/10714][stackexchange answer]].

#+begin_src emacs-lisp
  (defun my/org-remove-link ()
    "Remove an org link"
    (interactive)
    (if (org-in-regexp org-link-bracket-re 1)
        (save-excursion
          (let ((remove (list (match-beginning 0) (match-end 0))))
            (apply 'delete-region remove)))))
#+end_src

**** Replace Link

This function comes from this [[https://emacs.stackexchange.com/a/10714][stackexchange answer]].

#+begin_src emacs-lisp
  (defun my/org-replace-link-by-link-description ()
    "Replace an org link by its description or if empty its address"
    (interactive)
    (if (org-in-regexp org-link-bracket-re 1)
        (save-excursion
          (let ((remove (list (match-beginning 0) (match-end 0)))
                (description
                 (if (match-end 2)
                     (org-match-string-no-properties 2)
                   (org-match-string-no-properties 1))))
            (apply 'delete-region remove)
            (insert description)))))
#+end_src

**** org-mode Export: htmlize

htmlize is necessary to export code blocks to HTML.

#+begin_src emacs-lisp
  (use-package htmlize :ensure t :defer t)
#+end_src

**** COMMENT org-mode Appearance: org-modern

org-modern is a package that beautify org-mode. It changes the
appearance of header line, table, time stamp and other things.

After using it for a long time, I decide to disable this package. This
starts with the difficulty of distinguishing headers of different
levels, especially when the level number increases. I started a
discussion thread in the package's GitHub repository about this
issue. Then, when reading the README of the package again, I found
that the package is incompatible with lots of other functions, such as
~org-indent-mode~, ~org-num-mode~ and ~visual-wrap-prefix-mode~. I do
not use ~org-indent-mode~ anyway, but I sometimes use ~org-num-mode~
and ~visual-wrap-prefix-mode~. Considering ~org-modern~ only provides
aesthetics changes, I prefer actual functionality. Also, it renders
some characters using layers, which hides the actual characters. Not
being able to see what are actually there makes me feel a bit
insecure, but this is only my personal opinion.

#+begin_src emacs-lisp
  (use-package org-modern
    :ensure t
    :defer t
    :hook (org-mode . global-org-modern-mode))
#+end_src

**** org-mode & E-Mail: org-msg

#+begin_src emacs-lisp
  (use-package org-msg
    :ensure t
    :init
    (org-msg-mode)
    :config
    (setq
     org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \\n:t"
     org-msg-startup "hidestars indent inlineimages"
     ;; org-msg-greeting-fmt "\nHi%s,\n\n"
     ;; org-msg-recipient-names '(("jeremy.compostella@gmail.com" . "Jérémy"))
     ;; org-msg-greeting-name-limit 3
     org-msg-default-alternatives '((new		. (text html))
                                    (reply-to-html	. (text html))
                                    (reply-to-text	. (text)))
     org-msg-convert-citation t
     org-msg-signature "

  Regards,

  ,#+begin_signature
  --
  ,*Chang Xiaoduan*
  ,#+end_signature"))
#+end_src

**** orin

#+begin_src emacs-lisp
  (use-package orin :defer t
    :ensure (orin
             :type git :host github :repo "drcxd/orin"
             :files ("*.el"))
    :init
    (setq orin-dir "~/org-roam"
          orin-operating-mode 'modern))
#+end_src

*** COMMENT Benchmark

Some Emacs users don't care about bootstrap time, they claim that they
only launch Emacs once and never close it until they turn off the
computer. However, I prefer to maintain a reasonable startup
time. It's always a good idea not to pay for what you are not
using.

#+begin_src emacs-lisp
  (use-package benchmark-init
    :ensure t
    :init
    (require 'benchmark-init)
    :hook (after-init . benchmark-init/deactivate))
#+end_src

*** Tools

**** ripgrep

ripgrep is a multi-threaded version of grep. It is quite useful when
searching for certain text.

#+begin_src emacs-lisp
  (use-package ripgrep :defer t :ensure t)
#+end_src

**** wgrep

wgrep allows users to modify grep/ripgrep outputs and save the changes
to each output's original location. It is a really powerful
interactive text file editing tool.

#+begin_src emacs-lisp
  (use-package wgrep :defer t :ensure t)
#+end_src

**** scratch

This program allows user to create a scratch buffer of a certain mode,
so you can write anything in it.

#+begin_src emacs-lisp
  (use-package scratch
    :defer t
    :ensure t
    :init
    (defun my/scratch-with-prefix ()
      (interactive)
      (let ((current-prefix-arg '(0)))
        (call-interactively 'scratch)))
    :bind
    ("C-c s c" . my/scratch-with-prefix))
#+end_src

**** Transient

A tutorial about using transient. I tried to use transient to develop
a menu for my day-to-day workflow, but its manual is not intuitive for
me, so the idea has been infinitely delayed. Maybe someday I can use
this tutorial.

https://cocode.se/emacs/transient_cont.html

**** ghostel

#+begin_src emacs-lisp
  (use-package ghostel
    :ensure t
    :defer t)
#+end_src

**** COMMENT Pomodoro and Timers

Sometimes I use the [[https://en.wikipedia.org/wiki/Pomodoro_Technique][pomodoro technique]] to force myself focus on my
task. I have tried [[https://github.com/SqrtMinusOne/pomm.el][pomm]] but I do not like its behavior. It
automatically switch to the next state, while I want to do this
manually. Then I found [[https://github.com/TatriX/pomidor/][pomidor]], this is exactly what I wanted.

Sometimes I just want to set a timer, and I found [[https://github.com/protesilaos/tmr][tmr]]. It's simple and
easy to use.

#+begin_src emacs-lisp
  (use-package tmr
    :defer t
    :ensure t
    :init
    (if (eq system-type 'windows-nt)
        (progn
          (defun my/tmr-alert-notify (timer)
            (let ((title "TMR May Ring")
                  (body (tmr--long-description-for-finished-timer timer)))
              (alert body
                     :title title)))
          (setq tmr-timer-finished-functions (list #'my/tmr-alert-notify
                                                   #'tmr-print-message-for-finished-timer
                                                   #'tmr-acknowledge-minibuffer))))
    :bind
    (("C-c t T" . tmr)
     ("C-c t t" . tmr-with-details)
     ("C-c t r" . tmr-remove-finished)
     ("C-c t R" . tmr-remove)
     ("C-c t l" . tmr-tabulated-view)))

  (use-package pomidor
    :defer t
    :ensure t
    :bind (("C-c t p" . pomidor))
    :config
    (setq
     pomidor-sound-tick nil
     pomidor-sound-tack nil
     pomidor-seconds (* 30 60)
     pomidor-break-seconds (* 10 60)
     pomidor-long-break-seconds (* 25 60))
    (if (eq system-type 'windows-nt)
        (setq pomidor-alert (lambda ()
                              (let ((message (pomidor-default-alert-message)))
                                (when message
                                  (alert message :title "Pomidor")))))))
#+end_src

*** Window Management

***** zoom

By default, when multiple windows are displayed, Emacs split the
screen evenly among them. However, sometimes, this not what I
like. For example, when I am editing one buffer while reading the
content of another buffer, I may want to make the edited buffer takes
up most of the screen space. Emacs has a series of built-in commands
such as =enlarge-window= which allow users to adjust the window size as
they want. However, this process is repetitive and boring, because it
usually only enlarge/shrink the window by one row/column. zoom helps
me conveniently change the ration of windows sizes by simply execute
one single command.

#+begin_src emacs-lisp
  (use-package zoom
    :defer t
    :ensure t
    :config
    (setq zoom-size '(0.618 . 0.618))
    :bind
    ("C-c z" . zoom))
#+end_src

***** switch-window

#+begin_src emacs-lisp
  (use-package switch-window :ensure t
    :bind
    (("C-c o" . switch-window)
     ("C-c w d" . switch-window-then-delete)
     ("C-c w m" . switch-window-then-maximize)
     ("C-c w s" . switch-window-then-swap-buffer)
     ("C-c w b" . switch-window-then-display-buffer)
     ("C-c w f" . switch-window-then-find-file)
     ([remap other-window] . switch-window)))
#+end_src

*** Programming

**** flycheck

flycheck is an error checking package, which displays inline visual
hint for possible code warning or error. Currently, I only use it as
a facility for lsp.

#+begin_src emacs-lisp
  (use-package flycheck :defer t :diminish flycheck-mode :ensure t)
#+end_src

**** hl-todo

This package highlights certain keywords in comments and string
literals.

#+begin_src emacs-lisp
  (use-package hl-todo
    :ensure t
    :defer t
    :config
    (setq hl-todo-highlight-punctuation ":"
          hl-todo-keyword-faces
          `(("TODO" warning bold)
            ("FIXME" error bold)
            ("HACK" font-lock-constant-face bold)
            ("REVIEW" font-lock-keyword-face bold)
            ("NOTE" success bold)
            ("DEPRECATED" font-lock-doc-face bold)
            ("BUG" error bold)))
    :hook
    (prog-mode . hl-todo-mode))
#+end_src

**** git-gutter :dependency:

This packages add visual hint on the fringe to indicate which part of
the file is added/deleted/modified against the latest version in the
version control system.

#+begin_src emacs-lisp
  (use-package git-gutter
    :ensure t
    :diminish git-gutter-mode
    :defer t
    :config
    (setq git-gutter:handled-backends '(git svn))
    :hook
    (prog-mode . git-gutter-mode)
    :bind
    (("C-c v v" . git-gutter)
     ("C-c v n" . git-gutter:next-hunk)
     ("C-c v p" . git-gutter:previous-hunk)
     ("C-c v r" . git-gutter:revert-hunk)))
#+end_src

**** evil-nerd-commenter

Commenting a piece of code might be one of the most frequent
operations a programmer performs. Thus, we need a convenient and smart
package to help us perform this task. evil-nerd-commenter fits my
need.

#+begin_src emacs-lisp
  (use-package evil-nerd-commenter
    :ensure t
    :defer t
    :bind
    (("C-c c" . evilnc-comment-or-uncomment-lines)
     ("C-c C" . evilnc-copy-and-comment-lines)))
#+end_src

**** Language Server Protocols

Language server protocol is a powerful tool. It enables Eamcs provide
IDE-like functions, such as auto-completion,
jump-to-definition/declaration, find-references and even
variable-rename.

***** lsp-mode :dependency:

#+begin_src emacs-lisp
  (defun lsp-booster--advice-json-parse (old-fn &rest args)
    "Try to parse bytecode instead of json."
    (or
     (when (equal (following-char) ?#)
       (let ((bytecode (read (current-buffer))))
         (when (byte-code-function-p bytecode)
           (funcall bytecode))))
     (apply old-fn args)))


  (defun lsp-booster--advice-final-command (old-fn cmd &optional test?)
    "Prepend emacs-lsp-booster command to lsp CMD."
    (let ((orig-result (funcall old-fn cmd test?)))
      (if (and (not test?)                             ;; for check lsp-server-present?
               (not (file-remote-p default-directory)) ;; see lsp-resolve-final-command, it would add extra shell wrapper
               lsp-use-plists
               (not (functionp 'json-rpc-connection))  ;; native json-rpc
               (executable-find "emacs-lsp-booster"))
          (progn
            (when-let ((command-from-exec-path (executable-find (car orig-result))))  ;; resolve command from exec-path (in case not found in $PATH)
              (setcar orig-result command-from-exec-path))
            (message "Using emacs-lsp-booster for %s!" orig-result)
            (cons "emacs-lsp-booster" orig-result))
        orig-result)))
  (if (executable-find "emacs-lsp-booster")
      (progn
        (advice-add (if (progn (require 'json)
                               (fboundp 'json-parse-buffer))
                        'json-parse-buffer
                      'json-read)
                    :around
                    #'lsp-booster--advice-json-parse)
        (advice-add 'lsp-resolve-final-command :around #'lsp-booster--advice-final-command)))
#+end_src

#+begin_src emacs-lisp
  (use-package lsp-mode
    :ensure (lsp-mode :host github :repo "drcxd/lsp-mode")
    :defer t
    :init
    (setq lsp-headerline-breadcrumb-enable nil
          lsp-semantic-tokens-apply-modifiers nil
          lsp-semantic-tokens-enable t
          lsp-enable-on-type-formatting nil
          lsp-enable-snippet nil
          read-process-output-max (* 1024 1024)) ;; to increase lsp performance
    (defun my/orderless-dispatch-flex-first (_pattern index _total)
      (and (eq index 0) 'orderless-flex))
    (defun corfu-lsp-setup ()
      (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
            '(orderless))
      ;; Optionally configure the first word as flex filtered.
      (setq-local orderless-style-dispatchers (list #'my/orderless-dispatch-flex-first))
      ;; Optionally configure the cape-capf-buster.
      (setq-local completion-at-point-functions (list (cape-capf-buster #'lsp-completion-at-point)))
      (advice-add #'lsp-completion-at-point :around #'cape-wrap-noninterruptible))
    (with-eval-after-load 'orderless
      (with-eval-after-load 'corfu
        (with-eval-after-load 'cape
          (setq lsp-completion-provider :none)
          (add-hook 'lsp-completion-mode-hook #'corfu-lsp-setup))))
    ;; :config
    ;; Require emmylua_ls https://github.com/EmmyLuaLs/emmylua-analyzer-rust
    ;; (with-eval-after-load 'lsp-mode
    ;;   (lsp-register-client
    ;;    (make-lsp-client
    ;;     :new-connection (lsp-stdio-connection "emmylua_ls")
    ;;     :activation-fn (lsp-activate-on "lua")
    ;;     :priority 1
    ;;     :server-id 'emmylua-rust)))
    :hook
    (lua-mode . (lambda () (setq-local lsp-enable-indentation nil)))
    (lua-ts-mode . (lambda () (setq-local lsp-enable-indentation nil)))
    :bind
    (:map lsp-mode-map
          ("C-c l d" . lsp-find-declaration)
          ;; ("C-c l D" . lsp-find-definition)
          ("C-c l o" . lsp-clangd-find-other-file)
          ("C-c l r" . lsp-find-references)
          ("C-c l R" . lsp-workspace-restart)
          ("C-c l S" . lsp-workspace-shutdown)
          ("C-c l a" . lsp-execute-code-action)
          ("C-c l n" . lsp-rename)
          ("C-c l t" . lsp-semantic-tokens-mode)))

  (use-package lsp-ui
    :ensure (:repo "https://github.com/drcxd/lsp-ui" :branch "personal-fixes")
    :defer t
    :bind
    (:map lsp-ui-mode-map
          ("C-c l g" . lsp-ui-doc-glance)
          ("C-c l F" . lsp-ui-doc-focus-frame))
    :config
    (setq lsp-ui-doc-show-with-mouse nil))

  (use-package consult-lsp
    :ensure t
    :defer t
    :after (lsp-mode consult)
    :init
    (setq lsp-ui-doc-max-width 120)
    :bind
    (:map lsp-mode-map
          ("C-c l S" . consult-lsp-symbols)
          ("C-c l s" . consult-lsp-file-symbols)
          ("C-c l i" . consult-lsp-diagnostics)))

  (use-package lsp-clangd
    :defer t
    :config
    (setq lsp-clients-clangd-args
          '("--completion-style=detailed"
            "--header-insertion=never"
            "--function-arg-placeholders=0"
            "--background-index"
            "--background-index-priority=low"
            "--pch-storage=memory")))

  (add-to-list 'safe-local-eval-forms '(lsp))
#+end_src

****** Python in lsp-mode :dependency:

=lsp-mode= requires a dedicated package -- =lsp-pyright= -- for the
language server =pyright= or =basedpyright=, an open source
alternative for =pyright=.

#+begin_src emacs-lisp
  (use-package lsp-pyright
    :defer t
    :ensure t
    :custom (lsp-pyright-langserver-command "basedpyright"))
#+end_src

***** COMMENT eglot

eglot is the Emacs built-in client for language server protocol. It's
more lightweight than lsp-mode, and it had been lacking a feature I
always want, the semantic token highlighting. However, the feature is
merged into the package recently, and lsp-mode is experiencing a
completion problem, so I have to use eglot for a while.

The following code installs the latest version of eglot, rather than
the one built-in Emacs, because I am so eager to use the semantic
token highlighting. This requires I install other two packages:
jsonrpc and flymake.

#+begin_src emacs-lisp
  (use-package jsonrpc
    :ensure (jsonrpc
             :host github
             :repo "emacs-mirror/emacs"
             :files ("lisp/jsonrpc.el")))

  (use-package flymake
    :ensure (flymake
             :host github
             :repo "emacs-mirror/emacs"
             :files ("lisp/progmodes/flymake.el")))

  (use-package eglot
    :ensure (eglot
             :type git
             :host github
             :repo "emacs-mirror/emacs"    ; mirrors Savannah instantly
             :files ("lisp/progmodes/eglot.el" "etc/EGLOT-NEWS")))

  (use-package consult-eglot
    :ensure t
    :defer t)
#+end_src

****** Cons of eglot

******* Project management

One thing inconvenient in eglot is to work with nested projects. For
example, I have a C++ project in directory =MyCppProject=. In one of
it sub-directory =MyLuaProject=, there is a Lua project. Both are
managed by Subversion rather than Git. Then launch eglot in a lua file
will make it monitor all the files in =MyCppProject=, which is
unnecessary and performance degenerating. lsp-mode has its own idea of
project management. It stores the location of projects using functions
such as ~lsp-workspace-folders-add~. With eglot, I have to rely on
Emacs built-in project package. This makes navigating from the Lua
project to the C++ project difficult. To be specific, with lsp-mode,
Emacs knows only the C++ project, and the Lua files are considered
part of the C++ project. I can use ~project-find-file~ in a Lua file
buffer to navigate to a C++ file. lsp-mode knows that the Lua files
are itself a project so that it does not bother the Lua language
server with the files outside of =MyLuaProject=. With eglot, Emacs has
to know that =MyLuaProject= is a separate project, so that the
language server does not try to monitor the files outside of it. This,
makes navigating from a Lua file to a C++ file with
~project-find-file~ difficult, since the file search is done only
inside the directory =MyLuaProject=.

******* Poor against C/C++ macros

eglot does a poor job dealing with C/C++ macros. If a function's
declaration is generated by a template, it yields an error when
trying to fetch the document information of the function.

******* Semantic token mode does not work if language server delays too much

After open a file which the language server takes a long time to
process, eglot's semantic token mode, even enabled, can not properly
color the symbols.

**** dump-jump

#+begin_src emacs-lisp
  (use-package dumb-jump :ensure t
    :custom
    (dump-jump-prefer-searcher 'rg)
    (xref-show-definition-function #'consult-xref)
    :config
    (add-hook 'xref-backend-functions #'dumb-jump-xref-activate))
#+end_src

**** COMMENT Syntax Highlighting

Eamcs has built-in syntax highlighting support, however it is based on
regular expression. This means it would not be correct in every
situation.

lsp also provides syntax highlighting support. This requires a backend
server, and sometimes it is too heavy to practice. What if we are
editing a simple one-file program but still want better syntax
highlighting?

I find the package tree-sitter. Its solution is better than regular
expression but still not a full functional compiler. This means it is
better than the built-in syntax highlighting solution but still not
totally correct. However, it is light-weight enough, so it is still a
viable choice.

After Emacs 29, tree-sitter has been integrated into Emacs core. There
is no need to install these additional packages anymore. Instead,
Emacs need to be compiled with tree-sitter library. Also, users have
to compile language specific shared library themselves to support
specific language major mode.

#+begin_src emacs-lisp :tangle no
  (use-package tree-sitter
   :diminish
   :defer t
   :hook
   ((c-mode . tree-sitter-mode)
    (c++-mode . tree-sitter-mode)
    (lua-mode . tree-sitter-mode)
    (tree-sitter-after-on . tree-sitter-hl-mode)))

  (use-package tree-sitter-langs
   :defer t)
#+end_src

**** Programming Languages

***** Lua

Since Emacs provides built-in tree-sitter support, and it provides more accurate analysis than the major mode for Lua, I would use =lua-ts-mode= whenever possible.

#+begin_src emacs-lisp
  (use-package lua-mode :defer t :ensure t)
  ;; (add-to-list 'major-mode-remap-alist '(lua-mode . lua-ts-mode))
#+end_src

***** C#

Use =csharp-ts-mode= by default since it provides more consistent
syntax highlighting.

#+begin_src emacs-lisp
  (add-to-list 'major-mode-remap-alist '(csharp-mode . csharp-ts-mode))
#+end_src

***** Scheme

Scheme is a dialect of Lisp. It is also the language used in the book
/Structure and Interpretation of Computer Programs/ (SICP). Emacs
provide nice support for scheme language. It has a built-in package
scheme-mode. The command ~run-scheme~ starts an inferior scheme process
inside Emacs. After that, you can evaluate scheme expression in any
scheme-mode buffer. The expression is evaluated in the inferior scheme
process.

****** Use Scheme in org-mode

To execute scheme code in org-mode, org-babel's [[https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-scheme.html][document]] requires
[[https://www.nongnu.org/geiser/][Geiser]].

#+begin_src emacs-lisp
  (use-package geiser :defer t :ensure t)
#+end_src

Geiser is an Emacs front end of a Scheme interpreter, and it supports
multiple implementations. For more information about Geiser, check its
documentation in Emacs' INFO pages (after installing the package).

******* A Minor Issue

I was using org 9.5 and I found org-babel failed to execute scheme
code in org-mode buffer. After a simple search, I found one who had
encountered the same
issue. https://www.mail-archive.com/emacs-orgmode@gnu.org/msg142485.html

It turns out there is a bug in org and I have to upgrade it to version
9.6 to fix it.

****** Scheme Implementations

******* COMMENT Chicken :dependency:

The first scheme implementation I used is the [[https://call-cc.org/][chicken
compiler]]. According to its [[https://wiki.call-cc.org/emacs#builtin-scheme-support][documents]], to use it with Emacs built-in
support is easy.

#+begin_src emacs-lisp :tangle no
  (setq scheme-program-name "csi -:c")
#+end_src

However, it needs some additional setup to work with org-babel (see
its [[https://wiki.call-cc.org/emacs#geiser][documents]]). What's more, it does not support Windows platform
nicely. First, there is no pre-built binaries or installers. Though
MSYS2-MinGW 64 package manager could install a package, it is actually
not viable. I have to build the compiler myself. Second,
=chicken-install=, which is a prerequisite for it to work with
org-babel, cannot work correctly on Windows. Chicken requires users to
apply for an account to report bug, which is not convenient.

******* Chez :dependency:

After I have found that I cannot make chicken work with org-babel on
Windows, I switch to [[https://github.com/cisco/ChezScheme][Chez]]. It has nice Windows support, e.g. a Windows
installer. It also host a repository on github so it is easy to report
a bug. Finally, it does not require additional setup to work with
Emacs. The only thing I have to do is to expose its binary =scheme= in
the =PATH=, or customize ~geiser-chez-binary~.

#+begin_src emacs-lisp
  (use-package geiser-chez :defer t :ensure t)
#+end_src

******* COMMENT Racket :dependency:

If I am only using Scheme then Chez is good enough, however, I use
scheme mainly to learn SICP. SICP has some customized code which are
used as dependencies in some exercises. There is a Racket package
(https://docs.racket-lang.org/sicp-manual/index.html
https://github.com/sicp-lang/sicp) that implements these customized
code so that users do not have to input and evaluate them every time
they execute code depends on them. Thus, [[https://racket-lang.org/][Racket]] becomes a better
choice than Chez when learning SICP.

What makes things interesting is that Racket is not only an
implementation of Scheme, but also itself a programming
language. There is a major-mode package =racket-mode= for it. There is
also a specialized org-babel language support package for Racket:
[[https://github.com/hasu/emacs-ob-racket][eamcs-ob-racket]] , which is only available on github. If I want to use
this package, I have no other choice but use =git submodule= to link it
to my configuration repository.

Note that if you want to use =racket-mode= then you should not install
=geiser-racket=. These two packages conflict with each other on some
particular settings. For example, when opening a =.rkt= file, if
=geiser-racket= is installed, then it opens it in =scheme-mode=. This
prevents you use some of the functions provided by =racket-mode=, since
it requires the major mode being =racket-mode=.

Thus, I have to choose one of the two solutions: =geiser-racket= plus
native org-babel support for scheme; or =racket-mode= plus
=emacs-ob-racket=.

I have tried the latter for some time, because I tried to find a way
to use the Racket package for SIPC conveniently in
org-babel. =emacs-ob-racket= allows me to add a header argument to the
code block to declare that the code depends on the SICP package, while
the native support for Scheme language or =geiser-racket= does not
provide such features.

However, =racket-mode= and =eamcs-ob-racket= makes completion when editing
Racket code block difficult, comparing with =geiser-racket=. Actually,
there seems no completion in the org-mode code blocks at all. Thus, I
switch back to =geiser-racket=. This is also because I found that adding
~(require sicp)~ at the beginning of any org-mode Scheme code block
imports the code defined in the SICP package, which is almost equally
convenient as the header argument.

Note that evaluating a Scheme code block in org-mode may be slow. This
can be optimized by having a dedicated REPL for the org-mode
buffer. Thus, org-babel does not have to launch a new instance of
Racket backend each time you evaluate a code block.

#+begin_src emacs-lisp
  (use-package geiser-racket :defer t)
#+end_src

***** Graphviz Dot

#+begin_src emacs-lisp
  (use-package graphviz-dot-mode :defer t
    :ensure t
    :init
    (add-to-list 'org-src-lang-modes '("dot" . graphviz-dot)))
#+end_src

***** Racket

Racket is an implementation of [[Scheme]]. Though there is a package
=geiser-racket= which supports using Racket as the implementation of
scheme, it lacks maintenance now.

With =racket-mode= and =emacs-ob-racket=, I can use Racket as an
implementation of scheme in org mode, though not without troubles.

=racket-mode= requires enable =racket-xp-mode= to provide dynamic
completion. This does not work well with the org mode edit special
buffer. I have to manually execute ~racket-run~ once in a
edit-special-session to make =racket-xp-mode= works. =geiser-racket= is
much more convenient on the completion aspect, though it has severe
problem of correctly executing Racket code.

Thus, I decide to include both solutions in my configuration for now.

#+begin_src emacs-lisp
  (use-package ob-racket :defer t
    :after org
    :config
    (add-hook 'ob-racket-pre-runtime-library-load-hook
              #'ob-racket-raco-make-runtime-library)
    :ensure (ob-racket
             :type git :host github :repo "hasu/emacs-ob-racket"
             :files ("*.el" "*.rkt")))

  (use-package racket-mode :defer t
    :ensure t
    :hook
    (racket-mode . racket-xp-mode))
#+end_src

***** powershell

Since I mostly use Emacs on Windows platform, I need this package to
interact nicely with the OS. Emacs built-in eshell mode and term mode
does not work properly on Windows. This package also comes with a
powershell mode to help editing powershell script files.

#+begin_src emacs-lisp
  (use-package powershell :defer t :ensure t)
#+end_src

**** smartparens

Automatically insert/delete parenthesizes and replace matching
parenthesizes with other symbols...

#+begin_src emacs-lisp
  (use-package smartparens
    :ensure t
    :diminish smartparens-mode
    :hook
    (prog-mode text-mode)
    :config
    (require 'smartparens-config))
#+end_src

*** magit :dependency:

magit is the well-known Emacs interface for git.

#+begin_src emacs-lisp
  (use-package transient :ensure t :defer t)
  (use-package magit
    :ensure t
    :defer t)
#+end_src

*** Agents and Large Language Models

**** ECA :dependency:

I am not not fond of the current state of LLMs, but I have to admit
they are helpful tools. Currently there are multiple Emacs packages
that support working with LLMs. Some are built-upon agents, such as
agent-shell. Some are built-upon API keys and act like agents, such as
gptel. I have experimented with Editor Code Assistant which acts like
an agent and is mostly model indifferent. It is simple to install and
setup. Though billing by API is usually more expensive than by
subscription, I do not use LLMs too much and I can afford DeepSeek
API, so I will stick with ECA for a little while.

#+begin_src emacs-lisp
  (use-package eca
    :defer t
    :ensure t
    :hook
    (eca-chat-mode . turn-off-auto-fill)
    :init
    (setq eca-chat-use-side-window nil))
#+end_src

*** Reading & Writing

**** Filling and Wrapping

I use ~visual-line-fill-column-mode~ to center text consists of long
lines. It is mainly for writing prose rather than code.

#+begin_src emacs-lisp
  (use-package visual-fill-column
    :ensure t
    :defer t
    :config
    (advice-add 'text-scale-adjust :after #'visual-fill-column-adjust)
    :hook
    (visual-line-mode . visual-fill-column-for-vline)
    :init
    (add-hook 'visual-line-mode-hook #'visual-fill-column-for-vline)
    (setq visual-fill-column-center-text t
          visual-fill-column-width (+ fill-column 8)
          visual-fill-column-fringes-outside-margins nil
          visual-fill-column-adjust-for-text-scale t))

  (use-package unfill :defer t :ensure t
    :bind
    ("M-q" . unfill-toggle))
#+end_src

**** elfeed

I used to collect interesting blogs in my personal notes. However, the
problem is that I  always forget to revisit them unless I encounter
something reminds me of them. Now I learned that RSS feed solves my
problem perfectly, and I am going to use elfeed for it. Gnus may do
the same work, but elfeed seems more dedicated and easy to use.

#+begin_src emacs-lisp
  (use-package elfeed :defer t
    :ensure t
    :init
    (setq elfeed-feeds '(("https://www.filfre.net/feed/rss/" blog video-game)
                         ("https://hsu.cy/feed.xml" blog)
                         ("https://hnrss.org/bestcomments" HN)
                         ("https://sachachua.com/blog/category/emacs-news/feed/" emacs)
                         ("https://protesilaos.com/codelog.xml" blog emacs)
                         ("https://nonzerosum.games/rss.xml" blog video-game))
          elfeed-search-filter "@2weeks +unread"
          elfeed-tree-filter "@2weeks")
    :config
    (add-hook 'elfeed-new-entry-hook (elfeed-make-tagger :before "2 weeks ago"
                                                         :remove 'unread))
    :hook
    (elfeed-show-mode . visual-line-mode))
#+end_src

**** Citation

Currently I am using org-cite, citar plus citeproc to deal with
citation issues.

***** citar

#+begin_src emacs-lisp
  (use-package citar
    :ensure t
    :init
    (setq org-cite-global-bibliography '("~/org-roam/references.bib")
          org-cite-insert-processor 'citar
          org-cite-follow-processor 'citar
          org-cite-activate-processor 'citar
          citar-bibliography org-cite-global-bibliography
          org-cite-export-processors '((t . (csl "modern-language-association.csl"))))
    :hook
    (org-mode . citar-capf-setup))

  (use-package citar-embark
    ;; :defer t
    :ensure t
    :after (citar embark)
    ;; :no-require
    :diminish citar-embark-mode
    :config (citar-embark-mode))

  ;; You can get the csl style files from
  ;; https://github.com/citation-style-language/styles

  ;; (setq org-cite-csl-styles-dir "path/to/styles/dir")
#+end_src

Also, =org-cite-csl-styles-dir= must be set for the csl styles to work.

**** E-Books

***** COMMENT calibre

This is an alternative to calibredb. I prefer this package over
calibredb. I have added some custom functions to open the directory
that contains a book in Dired.

#+begin_src emacs-lisp
  (use-package calibre :defer t :ensure t)
    ;; :config
    ;; (use-package calibre-library
    ;;   :ensure nil
    ;;   :config
    ;;   (defun calibre-book--path (book)
    ;;     "Return the path to the directory of BOOK."
    ;;     (let ((path (calibre-book-path book)))
    ;;       (file-name-concat (calibre--library)
    ;;                         path)))
    ;;   (defun calibre-library-open-book-dir (book)
    ;;     "Open the directory of BOOK."
    ;;     (interactive (list (tabulated-list-get-id))
    ;;                  calibre-library-mode)
    ;;     (find-file (calibre-book--path book)))
    ;;   :bind
    ;;   (:map calibre-library-mode-map
    ;;         ("O" . calibre-library-open-book-dir))))
#+end_src

This package also requires some local settings, for example, we have
to specify the location of the library:

#+begin_src emacs-lisp :tangle no
  (setq calibre-libraries '(("nonficition" . "~/Documents/Non Fiction Library/")))
#+end_src

Also, we can specify an external program to open a certain format of a book:

#+begin_src emacs-lisp :tangle no
  (setq calibre-external-programs '((pdf . "acrobat")))
#+end_src

Otherwise, the book is opened inside Emacs.

***** COMMENT E-books reader

****** COMMENT nov

nov is a package that allows you read EPUB files inside Emacs.

#+begin_src emacs-lisp
  (use-package nov
    :ensure t
    :defer t
    :init
    (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
    (setq nov-text-width t)
    :hook
    (nov-mode . (lambda () (setq truncate-lines nil))))
#+end_src

****** reader :dependency:

reader is a package that provides enhanced =pdf= and =epub= reading
experience than packages such as doc-view, nov.el, and pdf-tools.

Like jinx-mode, reader also requires manually compile a shared library
to work. This also requires we manually compile it in MinGW64 shell on
Windows and put the =.dll= file into the load path of the package.

#+begin_src emacs-lisp
  (if (eq system-type 'windows-nt)
      (use-package reader
        :ensure '(reader :type git :host codeberg :repo "MonadicSheep/emacs-reader"))
    (use-package reader
      :ensure '(reader :type git :host codeberg :repo "MonadicSheep/emacs-reader"
                       :files ("*.el" "render-core.so")
                       ;; :pre-build (("make" "all")))))
                       :pre-build ((message "all")))))

  (with-eval-after-load 'meow
    (add-to-list 'meow-mode-state-list '(reader-outline-mode . motion)))
#+end_src

**** Typst :dependency:

Typst is a new markup language for typesetting document. The following
packages provides support for writing Typst document in Emacs.

#+begin_src emacs-lisp
  ;; tree sitter mode Typst
  (use-package typst-ts-mode :defer t
    :ensure (:type git :host codeberg :repo "meow_king/typst-ts-mode")
    :init
    (add-to-list 'org-src-lang-modes '("typst" . typst-ts)))

  ;; typst-preview provides live preview for Typst documents
  (use-package typst-preview :defer t
    :after websocket ;; typst-preview require websocket
    :ensure t)

  (use-package ox-typst :after org :ensure t)
#+end_src

**** Taking Notes

As a text editor, Emacs is a good place to take notes. There are also
packages helps you organize your notes. The most popular one is
org-roam. A lighter-weight choice is denote. These two packages are
often used to practice a note-taking methodology called [[https://zettelkasten.de/introduction/][Zettelkasten]].

***** COMMENT org-roam

#+begin_src emacs-lisp
  (use-package org-roam
    :ensure t
    :defer t
    :init
    (setq
     org-roam-database-connector 'sqlite-builtin
     org-roam-directory "~/org-roam/"
     org-roam-node-display-template (concat "${title} " (propertize "${tags}" 'face 'org-tag))
     org-roam-capture-templates '(("d" "default" plain "%?"
                                   :target
                                   (file+head "%<%Y%m%d%H%M%S>.org" "#+title: ${title}\n"))
                                  ("p" "private" plain "%?"
                                   :target
                                   (file+head "private/%<%Y%m%d%H%M%S>.org" "#+title: ${title}\n"))
                                  ("e" "capture" entry "* %?<%<%Y-%m-%d %a %H:%M>>"
                                   :target
                                   (file+head "%<%Y%m%d%H%M%S>.org" "#+title: ${title}\n")
                                   :prepend t
                                   :kill-buffer t))
     org-roam-dailies-capture-templates '(("d" "default" plain "%?"
                                           :target
                                           (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d %A>\n"))))

    (defun my/title->file-name (title)
      "Process the input string so that it only contains valid
  characters for file names and is no more than 32 characters."
      (string-limit (replace-regexp-in-string file-name-invalid-regexp "" title) 32))

    (defun my/org-roam-rename-file ()
      "Rename the current org-roam file according to its title field."
      (if (org-roam-buffer-p)
          (let ((title (org-roam-db--file-title))
                (full-name (buffer-file-name)))
            (let ((new-name (format "%s.org" (my/title->file-name title)))
                  (current-name (file-name-nondirectory full-name)))
              (if (not (string= new-name current-name))
                  (if (file-exists-p current-name)
                      (warn (format "File %s already exists. Renaming skipped!" current-name))
                    (if (file-exists-p current-name)
                        (rename-file buffer-file-name new-name))
                    (set-visited-file-name new-name)))))))

    (defun my/org-roam-rename-buffer (&optional buffer)
      "Try to rename the current buffer if it is an org roam buffer and
  has a title. If possible, rename it using both its title and tags."
      (if (and (org-roam-buffer-p)
               (buffer-file-name))
          (save-excursion
            (goto-char (point-min))
            (let ((node (org-roam-node-at-point)))
              (if node
                  (let ((tags (org-roam-node-tags node))
                        (title (org-roam-node-title node)))
                    (if title
                        (rename-buffer (format "%s%s"
                                               title
                                               (apply #'concat
                                                      (seq-map (lambda (tag) (format " #%s" tag)) tags)))
                                       t)
                      (let ((title (org-roam-db--file-title)))
                        (if (> (length title) 0)
                            (rename-buffer title t))))))))))

    ;; This is inspired by denote's denote-rename-buffer-mode
    (define-minor-mode org-roam-rename-buffer-file-mode
      "Minor mode rename org mode buffer when opening org roam files,
  creating new org roam nodes, and saving org roam files."
      :global t
      (if org-roam-rename-buffer-file-mode
          (progn
            (add-hook 'org-roam-find-file-hook #'my/org-roam-rename-buffer)
            (add-hook 'org-roam-capture-new-node-hook #'my/org-roam-rename-buffer)
            ;; (add-hook 'before-save-hook #'my/org-roam-rename-file)
            (add-hook 'after-save-hook #'my/org-roam-rename-buffer))
        (remove-hook 'org-roam-find-file-hook #'my/org-roam-rename-buffer)
        (remove-hook 'org-roam-capture-new-node-hook #'my/org-roam-rename-buffer)
        ;; (remove-hook 'before-save-hook #'my/org-roam-rename-file)
        (remove-hook 'after-save-hook #'my/org-roam-rename-buffer)))

    (defun my/org-roam-capture-default ()
      "Simply org-roam-capture with the default template."
      (interactive)
      (org-roam-capture nil "d"))
    :config
    (org-roam-rename-buffer-file-mode)
    (org-roam-db-autosync-mode)
    :bind
    (("C-c n f" . org-roam-node-find)
     ("C-c n i" . org-roam-node-insert)
     ("C-c n t" . org-roam-tag-add)
     ("C-c n T" . org-roam-tag-remove)
     ("C-c n r" . org-roam-ref-add)
     ("C-c n R" . org-roam-ref-remove)
     ("C-c n b" . org-roam-buffer-toggle)
     ("C-c n B" . org-roam-buffer)
     ("C-c n a" . org-roam-alias-add)
     ("C-c n A" . org-roam-alias-remove)
     ("C-c n y" . org-roam-db-sync)
     ("C-c n C" . org-roam-capture)
     ("C-c n c" . my/org-roam-capture-default)
     ("C-c n F" . org-roam-refile)
     ("C-c n d d" . org-roam-dailies-goto-date)
     ("C-c n d o" . org-roam-dailies-goto-today)
     ("C-c n d y" . org-roam-dailies-goto-yesterday)
     ("C-c n d t" . org-roam-dailies-goto-tomorrow)
     ("C-c n d n" . org-roam-dailies-goto-next-note)
     ("C-c n d p" . org-roam-dailies-goto-previous-note)
     ("C-c n d c d" . org-roam-dailies-capture-date)
     ("C-c n d c o" . org-roam-dailies-capture-today)
     ("C-c n d c y" . org-roam-dailies-capture-yesterday)
     ("C-c n d c t" . org-roam-dailies-capture-tomorrow)))
#+end_src

****** consult-org-roam

Utility package makes org-roam using consult to search notes, forward
and backward links. It improves the workflow and thus efficiency.

#+begin_src emacs-lisp
  (use-package consult-org-roam
    :ensure t
    :after (org-roam consult)
    :diminish consult-org-roam-mode
    :init
    (setq consult-org-roam-buffer-enabled nil)
    ;; Activate the minor mode
    (consult-org-roam-mode 1)
    :custom
    ;; Use `ripgrep' for searching with `consult-org-roam-search'
    (consult-org-roam-grep-func #'consult-ripgrep)
    ;; Configure a custom narrow key for `consult-buffer'
    (consult-org-roam-buffer-narrow-key ?r)
    ;; Display org-roam buffers right after non-org-roam buffers
    ;; in consult-buffer (and not down at the bottom)
    ;; (consult-org-roam-buffer-after-buffers t)
    :config
    ;; Eventually suppress previewing for certain functions
    ;; (consult-customize
    ;;  consult-org-roam-forward-links
    ;;  :preview-key (kbd "M-."))
    :bind
    ;; Define some convenient keybindings as an addition
    ;; ("C-c n f" . consult-org-roam-file-find)
    ("C-c n l" . consult-org-roam-backlinks)
    ("C-c n L" . consult-org-roam-forward-links)
    ("C-c n s" . consult-org-roam-search))
#+end_src

****** citar-org-roam

A necessary package to integrate citar with org-roam, thus,
bibliographic notes can be easily created in org-roam context.

#+begin_src emacs-lisp
  (use-package citar-org-roam
    :ensure t
    :diminish citar-org-roam-mode
    :after (citar org-roam)
    ;; :no-require
    :config
    ;; Redefine citar-org-roam-setup to skip the call to org-roam-db-sync
    (defun citar-org-roam-setup ()
      "Setup `citar-org-roam-mode'."
      (citar-register-notes-source
       'citar-org-roam citar-org-roam-notes-config)
      (setq citar-notes-source 'citar-org-roam))
    (citar-org-roam-mode)
    (add-to-list 'org-roam-capture-templates '("r" "reference" plain "%?" :target
                                               (file+head "%<%Y%m%d%H%M%S>.org" "#+title: ${note-title}\n")
                                               :unnarrowed t) t)
    (setq citar-org-roam-capture-template-key "r"))
#+end_src

***** vulpea

#+begin_quote
Vulpea is a database layer for your org-mode notes.
#+end_quote

It provides better database functions than org roam. For example, org
roam does not update the database when note files are modified by
external processes such as git. Vulpea also performance better than
org roam in my opinion, though I have not verified this.

However, vulpea lacks some functions provided by org-roam and its
companion packages such as citar-org-roam. For example, org-roam
provides multiple capture templates which allows users to capture
files to different locations easily. Vulpea still lacks this feature
and users have to write customized code to implement it themselves. Of
course it is not vulpea's fault, since its purpose is to be library
rather than an application. As a result, from a user's perspective, I
can not use it to replace org roam fully now.

#+begin_src emacs-lisp
  (use-package vulpea :ensure t
    :demand t
    :init
    (setq vulpea-db-sync-directories '("~/org-roam"
                                       "~/org-roam/private"
                                       "~/org-roam/daily")
          vulpea-default-notes-directory "~/org-roam"
          vulpea-buffer-alias-property "ROAM_ALIASES"
          vulpea-db-async-extraction 'full)
    (defun vulpea-rename-buffer (&optional buffer)
      "Try to rename the current buffer it is a org-mode buffer visiting a note
  managed by vulpea. Rename it with its title and tags."
      (if (and (eq major-mode 'org-mode)
               (buffer-file-name))
          (save-excursion
            (let* ((id-values (org-property-values "ID"))
                   (id (if id-values
                           (car id-values)))
                   (note (if id
                             (vulpea-db-get-by-id id))))
              (if note
                  (let* ((title (vulpea-note-title note))
                         (tags (vulpea-note-tags note))
                         (buffer-name (format "%s%s"
                                              title
                                              (apply #'concat (seq-map (lambda (tag) (format " #%s" tag)) tags)))))
                    (rename-buffer buffer-name t)))))))
    (define-minor-mode vulpea-rename-buffer-mode
      "Minor mode that renames org mode buffer if it is a note managed by
  vulpea."
      :global t
      (if vulpea-rename-buffer-mode
          (progn
            (add-hook 'find-file-hook #'vulpea-rename-buffer)
            (add-hook 'after-save-hook #'vulpea-rename-buffer))
        (remove-hook 'find-file-hook #'vulpea-rename-buffer)
        (remove-hook 'after-save-hook #'vulpea-rename-buffer)))
    :bind
    (("C-c v f" . vulpea-find)
     ("C-c v i" . vulpea-insert))
    :config
    (vulpea-db-autosync-mode +1)
    (vulpea-rename-buffer-mode)
    (setq vulpea-create-default-template
          '(:file-name "${timestamp}.org"))

    (defun my/vulpea-create-private (title)
      (interactive "sTitle: ")
      (vulpea-visit (vulpea-create title
                                   (format "private/%s.org" (format-time-string "%Y%m%d%H%M%S"))))))

  (elpaca-wait) ;; wait because vulpea-ui depends on vulpea

  (use-package vulpea-ui
    :ensure t
    :after vulpea
    :demand t
    :init
    (setq vulpea-ui-sidebar-size 0.4
          vulpea-ui-sidebar-position 'left)
    :bind
    ("C-c v s" . vulpea-ui-sidebar-toggle))

  (elpaca-wait) ;; wait because vulpea-journal depends on vulpea and vulpea-ui

  (use-package vulpea-journal
    :ensure t
    :demand t
    :after (vulpea vulpea-ui)
    :bind
    (("C-c v j" . vulpea-journal)
     ("C-c v J" . vulpea-journal-date))
    :config
    (vulpea-journal-setup)
    (setq vulpea-journal-default-template
          (vulpea-journal-template-daily
           :file-name "daily/%Y-%m-%d.org"
           :title "%Y-%m-%d %A")))

  (use-package citar-vulpea
    :ensure t
    :diminish citar-vulpea-mode
    :after (vulpea citar)
    :custom
    (citar-vulpea-keyword "bib")
    (citar-vulpea-references-property "ROAM_REFS")
    :config
    (citar-vulpea-mode 1))

  ;; (use-package consult-vulpea
  ;;   :ensure t
  ;;   :after (consult vulpea))

  (use-package embark-vulpea
    :ensure (:repo "https://github.com/fabcontigiani/embark-vulpea")
    :after (embark vulpea))
#+end_src

To use vulpea, I must implement the functions provided by org-roam by
myself. It may not be difficult but it definitely requires some
effort. To list some of the features I need to implement:

1. Capture to a certain file with some template content.
2. Add/Remove tags to/from a file.
3. Citar integration.


I come up with some code to implement feature 1:

#+begin_src emacs-lisp :tangle no
  (setq org-capture-templates
        `(("n" "Create a new note file."
           plain
           (file ,(lambda ()
                    (file-name-concat
                     org-directory
                     (format-time-string "%Y%m%d%H%M%S.org"))))
           ":PROPERTIES:
  :ID: %(org-id-new)
  :END:
  ,#+title: %^{title}

  ")))
#+end_src

For feature 2, I can implement a function to ask for file
tags. However, it is not trivial to provide completion for all
existing tags.

Feature 3 also requires reading the documentation and code of citar.

**** Input Method -- pyim

#+begin_src emacs-lisp
  (use-package pyim :ensure t
    :defer t
    :init
    (setq default-input-method "pyim")
    :config
    ;; Disable pyim when not in meow-insert-mode
    (with-eval-after-load 'meow
      (setq-default pyim-english-input-switch-functions
                    `((lambda () (and (not meow-insert-mode)
                                      (not (minibufferp))))))))
  (use-package pyim-wbdict :ensure t
    :after pyim
    :config
    (setq pyim-default-scheme 'wubi)
    (pyim-wbdict-v98-enable))
#+end_src

**** Spell Checking

***** jinx :dependency:

To use jinx, you have to install =enchant= on your system. It also
relies on dictionary packages such as =aspell_en=.

Using jinx on Windows requires manual compilation of the dynamic
library. Without the dll file, when jinx is enabled, it tries to
compile it. It fails due to the compilation command is written for
Linux systems:

#+begin_example
  gcc -I. -O2 -Wall -Wextra -fPIC -shared -o jinx-mod.dll jinx-mod.c -I/usr/include/enchant-2 -I/usr/local/include/enchant-2 -L/usr/local/lib -lenchant-2
#+end_example

We can install =enchant= on MinGW64, and the library is usually
located at =msys64/mingw64/include/enchant-2=. Thus, we have to
manually compile the dll using the following command in MinGW64 shell:

#+begin_example
  gcc -I. -O2 -Wall -Wextra -fPIC -shared -o jinx-mod.dll jinx-mod.c -I/mingw64/lib/enchant-2 -L/usr/local/lib -lenchant-2
#+end_example

Finally, we have to put the =.dll= file to the load path of the jinx package.

#+begin_src emacs-lisp
  (use-package jinx
    :ensure t
    :diminish
    :defer t
    :init
    (setq jinx-languages "en_US")
    :config
    (add-to-list 'jinx-exclude-regexps '(t "\\cc"))
    :hook
    ((text-mode . jinx-mode)
     (prog-mode . jinx-mode))
    :bind
    (("C-." . jinx-correct)))
#+end_src

***** emacs-ltex-plus :dependency:

LTex+ is a grammar/spell checking tool. It is more advanced than
simple spell checking tools since it can detect improper language
usage. The checker program run totally offline, so there is no privacy
concerns. However, the performance on large files is not ideal. After
I edit this file, it takes tens of seconds for the server to
synchronize. Thus, I decide to use this with jinx-mode and only enable
it for prose writing.

#+begin_src emacs-lisp
  (use-package lsp-ltex-plus :defer t
    :ensure (:repo "https://github.com/alberti42/emacs-ltex-plus")
    :init
    (setq lsp-ltex-plus-additional-rules-enable-picky-rules t))
          ;; lsp-ltex-plus-show-latency t
          ;; lsp-ltex-plus-debug t))
#+end_src

**** Publishing

#+begin_src emacs-lisp
  (defvar my/publish-tag "publish"
    "Tag that marks the files require publishing.")

  (defvar my/posts-dir "~/data/workplace/blog/posts"
    "Directory to store published notes.")

  (defun my/publish-notes (tag &optional dst-dir)
    "Export note files that contains `tag' as one of its file tags in
  `org-roam-directory' as HTML files and move them to `dst-dir' if
  provided."
    (dolist (file (directory-files org-roam-directory))
      (if (string-suffix-p ".org" file)
          (with-temp-buffer
            (let* ((org-name (file-name-concat org-roam-directory file))
                   (html-name (file-name-with-extension org-name "html")))
              (insert-file-contents org-name)
              (let ((beg (or (search-forward "#+filetags: " nil t)
                             (search-forward "#+FILETAGS: " nil t))))
                (if beg
                    (let* ((end (line-end-position))
                           (tags (buffer-substring beg end)))
                      (if (string-match-p tag tags)
                          (let* ((name-nondir (file-name-nondirectory html-name))
                                 (dst-name (file-name-concat dst-dir name-nondir))
                                 (org-html-postamble nil))
                            (org-export-to-file 'html html-name)
                            (if dst-dir
                                (rename-file html-name dst-name t))))))))))))

  (defun my/publish-notes-helper ()
    "Helper functions that export all notes tagged with `my/publish-tag' to
  directory `my/posts-dir'."
    (interactive)
    (my/publish-notes my/publish-tag my/posts-dir))

  (defun my/publish-current-note ()
    "Publish current org roam note file to `my/post-dir' as HTML file."
    (interactive)
    (let* ((org-html-postamble nil)
           (html-file (org-html-export-to-html))
           (name-nondir (file-name-nondirectory html-file))
           (dst-name (file-name-concat my/posts-dir name-nondir)))
      (rename-file html-file dst-name t)))
#+end_src

**** org-markdown-preview

This package supports live previewing org/markdown buffer using your
web browser or xwidget if Emacs is compiled with support for it.

#+begin_src emacs-lisp
  (use-package ghub :ensure t :defer t)

  (use-package org-markdown-preview
    :defer t
    :ensure (:repo "https://github.com/KarimAziev/org-markdown-preview"
                   :files ("*.el" "*.html"))
    :commands (org-markdown-preview-mode))
#+end_src

*** Entertainment

**** i-ching

This package simulates the divination process described by I-Ching. It
is interesting to experiment sometimes. I also intend to expand this
package so that it contains the original Chinese text for the
hexagrams.

#+begin_src emacs-lisp
  (use-package i-ching :defer t
    :ensure t
    :init
    (setq i-ching-randomness-source 'atmospheric))
#+end_src

*** Editing

**** avy

avy is a package I find useful for navigating around text. It help
reduce repeatedly moving cursor to the next line, next char. Using
avy, I can first think about where I want to place my cursor and then
navigate to there with a feel keystrokes. It also can move cursor
across windows, so I do not have to first =C-x o= to switch to other
window then start moving cursor around.

#+begin_src emacs-lisp
  (use-package avy
    :ensure t
    :init
    (avy-setup-default)
    :bind
    (("<f9>" . avy-goto-word-1)
     ("C-c a b" . avy-goto-line)
     ("C-c a e" . avy-goto-end-of-line)
     ("C-c a c" . avy-goto-char-2)))
#+end_src

**** occult

occult allows collapsing arbitrary region into one single line of
text, which is a nice complementary package to hideshow.

#+begin_src emacs-lisp
  (use-package occult
    :defer t
    :diminish occult--mode
    :ensure (:repo "https://github.com/drcxd/occult.el"
                   :branch "pfixes"))
#+end_src

**** meow

meow is a modal editing package. It looks like evil, but I think it
suits Emacs more than evil. meow provides supports for many Emacs
packages native key bindings, such as org-mode. For example, when
using meow, you can execute the command =org-babel-tangle= by pressing
=SPC c v t= out-of-the-box, while its original key binding is =C-c C-v
t=. It also works well with my own native key bindings. When using
meow, I do not have to change my original key binding settings. I only
add some additional configuration specific to meow.

#+begin_src emacs-lisp
  (use-package meow
    :ensure t
    :demand t
    :init
    (defun meow-setup ()
      (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
      ;; (meow-motion-overwrite-define-key
      ;;  ;; '("j" . meow-next)
      ;;  ;; '("k" . meow-prev)
      ;;  '("<escape>" . ignore))
      (meow-leader-define-key
       ;; SPC j/k will run the original command in MOTION state.
       ;; '("j" . "H-j")
       ;; '("k" . "H-k")
       ;; Use SPC (0-9) for digit arguments.
       '("1" . meow-digit-argument)
       '("2" . meow-digit-argument)
       '("3" . meow-digit-argument)
       '("4" . meow-digit-argument)
       '("5" . meow-digit-argument)
       '("6" . meow-digit-argument)
       '("7" . meow-digit-argument)
       '("8" . meow-digit-argument)
       '("9" . meow-digit-argument)
       '("0" . meow-digit-argument)
       '("/" . meow-keypad-describe-key)
       '("?" . meow-cheatsheet))
      (meow-normal-define-key
       '("0" . meow-expand-0)
       '("9" . meow-expand-9)
       '("8" . meow-expand-8)
       '("7" . meow-expand-7)
       '("6" . meow-expand-6)
       '("5" . meow-expand-5)
       '("4" . meow-expand-4)
       '("3" . meow-expand-3)
       '("2" . meow-expand-2)
       '("1" . meow-expand-1)
       '("-" . negative-argument)
       '(";" . meow-reverse)
       '("," . meow-inner-of-thing)
       '("." . meow-bounds-of-thing)
       '("[" . meow-beginning-of-thing)
       '("]" . meow-end-of-thing)
       '("a" . meow-append)
       '("A" . meow-open-below)
       '("b" . meow-back-word)
       '("B" . meow-back-symbol)
       '("c" . meow-change)
       '("d" . meow-delete)
       '("D" . meow-backward-delete)
       '("e" . meow-next-word)
       '("E" . meow-next-symbol)
       '("f" . meow-find)
       '("g" . meow-cancel-selection)
       '("G" . meow-grab)
       '("h" . meow-block)
       '("H" . meow-to-block)
       '("i" . meow-prev)
       '("I" . meow-prev-expand)
       '("j" . meow-left)
       '("J" . meow-left-expand)
       '("k" . meow-next)
       '("K" . meow-next-expand)
       '("l" . meow-right)
       '("L" . meow-right-expand)
       '("m" . meow-join)
       '("n" . meow-search)
       '("o" . meow-insert)
       '("O" . meow-open-above)
       '("p" . meow-yank)
       '("P" . meow-yank-pop)
       '("q" . evilnc-comment-or-uncomment-lines)
       '("Q" . evilnc-copy-and-comment-lines)
       '("r" . meow-replace)
       '("R" . meow-swap-grab)
       '("s" . meow-kill)
       '("t" . meow-till)
       '("u" . meow-undo)
       '("U" . meow-undo-in-selection)
       '("v" . meow-visit)
       '("w" . meow-mark-word)
       '("W" . meow-mark-symbol)
       '("x" . meow-line)
       '("X" . meow-goto-line)
       '("y" . meow-save)
       '("Y" . meow-sync-grab)
       '("z" . meow-pop-selection)
       '("'" . repeat)
       '("<escape>" . ignore)
       '("=" . indent-region)
       '("`" . delete-horizontal-space)
       '("{" . backward-paragraph)
       '("}" . forward-paragraph)
       '("/" . hs-toggle-hiding)
       '("\\" . occult-toggle))
      ;; disable SPC in motion mode since it might be used
      (define-key meow-motion-state-keymap (kbd "SPC") nil))
    (setq meow-replace-state-name-list '((normal . "[N]")
                                         (motion . "[M]")
                                         (keypad . "[K]")
                                         (insert . "[I]")
                                         (beacon . "[B]"))
          meow-keypad-leader-dispatch "C-c"
          meow-mode-state-list '((fundamental-mode . normal)
                                 (text-mode . normal)
                                 (prog-mode . normal)
                                 (conf-mode . normal)
                                 (bibtex-mode . normal))
          meow-use-clipboard t
          meow-keypad-describe-keymap-function nil)
    :config
    ;; use motion state by default
    (defun my/meow-guess-state (state) 'motion)
    (advice-add 'meow--mode-guess-state :filter-return #'my/meow-guess-state)
    (meow-setup)
    (meow-global-mode 1)
    (global-set-key (kbd "<f5>") 'meow-keypad)
    :hook
    (meow-insert-exit . (lambda ()
                          (if (and meow-normal-mode (not buffer-read-only))
                              (delete-trailing-whitespace (pos-bol) (pos-eol))))))
#+end_src

***** A Note About KEYPAD Mode

Meow's default behavior is to add =C-`= prefix to any key with no
prefix. This looks counter-intuitive to me. Meow is trying to simulate
Emacs native key bindings, but this behavior is the contrary of Emacs
native style. For example, command =view-echo-area-message= is bound to
=C-h e=, and command =view-external-packages= is bound to =C-h
C-e=. Translated into Meow, =view-echo-area-message= is bound to =SPC h
SPC e=, while =view-external-packages= is bound to =SPC h
e=. =view-external-packages= has more key strokes in native key bindings,
but has less key stokes in Meow. =view-echo-area-message= has less key
strokes in native key bindings, but has more key strokes in Meow.

Also, Meow has a fallback mechanism. Meow maps =C-h k= to =SPC h SPC k=,
and =C-h C-k= to =SPC h k=. However, when =C-h C-k= is unbound, =SPC h k= will
automatically invokes the command bound to =C-h k=. This is convenient,
but it introduces uncertainty. Meow users could not know the command
=SPC h k= invokes is bound to which native key binding: =C-h C-k= or =C-h
k=.

The author's explanation for this behavior is [[https://github.com/meow-edit/meow/issues/47#issuecomment-1377206836][here]]. I try to
understand and accept the author's idea, but I still found that if
KEYPAD does not automatically add =C-= prefix would be better. I have
asked the author to add an option to let users make their own choices,
but the author seems not agree with me.

Thus, I tried to dig into the source code and modify them by
myself. In =meow-keypad.el=, there is a function
=meow-keypad-self-insert=, which defines how KEYPAD translate key
strokes. If we exchange the code dealing with literal and non-prefix
cases, then we change KEYPAD's behavior to not automatically add =C-=
prefix, but only when =SPC= is pressed. This modification introduces a
new problem: which-key prompt for KEYPAD key bindings does not update
to fit this change. There are two additional functions
=meow--keypad-format-keys= and =meow--keypad-get-keymap-for-describe=, they all
have similar structures to that of =meow-keypad-self-insert=, deal with
them so that Meow generate the correct hints.

*** Finalizing

#+begin_src emacs-lisp
  ;; wait for elpaca until all packages are installed since some code in
  ;; the custom file may depend on some packages
  (elpaca-wait)
#+end_src

* Keyboard Macros

Since keyboard macros may depends on built-in or third party packages,
I put them here.

To add new keyboard macros, first name the keyboard macros with
~kmacro-name-last-macro~, then insert its definition with
~insert-kbd-macro~.

#+begin_src emacs-lisp
  (defalias 'my/default-window-layout
     (kmacro "C-x 1 C-x 3 C-x o C-x 2 C-x o 3 C-c z"))
#+end_src

* Load Custom File

Finally, after all the other settings have been done, we load the
local customization file.

#+begin_src emacs-lisp
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src
